/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type InternalServerErrorError = {
  code: string;
  message: string;
  details?: any | undefined;
};

/**
 * Internal Server Error
 */
export type InternalServerErrorData = {
  success: boolean;
  error: InternalServerErrorError;
};

/**
 * Internal Server Error
 */
export class InternalServerError extends Error {
  success: boolean;
  error: InternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: InternalServerErrorData;

  constructor(err: InternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "InternalServerError";
  }
}

export type NotFoundErrorResponse = {
  code: string;
  message: string;
  details?: any | undefined;
};

/**
 * Products Not Found
 */
export type GetProductsNotFoundErrorData = {
  success: boolean;
  error: NotFoundErrorResponse;
};

/**
 * Products Not Found
 */
export class GetProductsNotFoundError extends Error {
  success: boolean;
  error: NotFoundErrorResponse;

  /** The original data that was passed to this error instance. */
  data$: GetProductsNotFoundErrorData;

  constructor(err: GetProductsNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "GetProductsNotFoundError";
  }
}

export type UnauthorizedErrorResponse = {
  code: string;
  message: string;
  details?: any | undefined;
};

/**
 * Unauthorized
 */
export type GetProductsUnauthorizedErrorData = {
  success: boolean;
  error: UnauthorizedErrorResponse;
};

/**
 * Unauthorized
 */
export class GetProductsUnauthorizedError extends Error {
  success: boolean;
  error: UnauthorizedErrorResponse;

  /** The original data that was passed to this error instance. */
  data$: GetProductsUnauthorizedErrorData;

  constructor(err: GetProductsUnauthorizedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "GetProductsUnauthorizedError";
  }
}

export type BadRequestErrorResponse = {
  code: string;
  message: string;
  details?: any | undefined;
};

/**
 * Bad Request
 */
export type GetProductsBadRequestErrorData = {
  success: boolean;
  error: BadRequestErrorResponse;
};

/**
 * Bad Request
 */
export class GetProductsBadRequestError extends Error {
  success: boolean;
  error: BadRequestErrorResponse;

  /** The original data that was passed to this error instance. */
  data$: GetProductsBadRequestErrorData;

  constructor(err: GetProductsBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "GetProductsBadRequestError";
  }
}

export type UnprocessableEntityErrorResponse = {
  issues: Array<Issue>;
  name: string;
};

export type ResponseBodyError2Data = {
  success: boolean;
  error: UnprocessableEntityErrorResponse;
};

export class ResponseBodyError2 extends Error {
  success: boolean;
  error: UnprocessableEntityErrorResponse;

  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError2Data;

  constructor(err: ResponseBodyError2Data) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "ResponseBodyError2";
  }
}

export type PatchProductsIdPath1 = string | number;

export type Issue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export type ResponseBodyUnprocessableEntityError = {
  issues: Array<Issue>;
  name: string;
};

export type ResponseBodyError1Data = {
  success: boolean;
  error: ResponseBodyUnprocessableEntityError;
};

export class ResponseBodyError1 extends Error {
  success: boolean;
  error: ResponseBodyUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError1Data;

  constructor(err: ResponseBodyError1Data) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "ResponseBodyError1";
  }
}

/**
 * The validation error(s)
 */
export type PatchProductsIdUnprocessableEntity =
  | ResponseBodyError1
  | ResponseBodyError2;

/**
 * Invalid Id Error
 */
export type DeleteProductsIdUnprocessableEntityErrorData = {
  success: boolean;
  error: UnprocessableEntityErrorResponse;
};

/**
 * Invalid Id Error
 */
export class DeleteProductsIdUnprocessableEntityError extends Error {
  success: boolean;
  error: UnprocessableEntityErrorResponse;

  /** The original data that was passed to this error instance. */
  data$: DeleteProductsIdUnprocessableEntityErrorData;

  constructor(err: DeleteProductsIdUnprocessableEntityErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "DeleteProductsIdUnprocessableEntityError";
  }
}

/**
 * The validation error(s)
 */
export type PatchCustomersIdUnprocessableEntity =
  | ResponseBodyError1
  | ResponseBodyError2;

/**
 * The validation error(s)
 */
export type PatchTransactionsIdUnprocessableEntity =
  | ResponseBodyError1
  | ResponseBodyError2;

/** @internal */
export const InternalServerErrorError$inboundSchema: z.ZodType<
  InternalServerErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/** @internal */
export type InternalServerErrorError$Outbound = {
  code: string;
  message: string;
  details?: any | undefined;
};

/** @internal */
export const InternalServerErrorError$outboundSchema: z.ZodType<
  InternalServerErrorError$Outbound,
  z.ZodTypeDef,
  InternalServerErrorError
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InternalServerErrorError$ {
  /** @deprecated use `InternalServerErrorError$inboundSchema` instead. */
  export const inboundSchema = InternalServerErrorError$inboundSchema;
  /** @deprecated use `InternalServerErrorError$outboundSchema` instead. */
  export const outboundSchema = InternalServerErrorError$outboundSchema;
  /** @deprecated use `InternalServerErrorError$Outbound` instead. */
  export type Outbound = InternalServerErrorError$Outbound;
}

export function internalServerErrorErrorToJSON(
  internalServerErrorError: InternalServerErrorError,
): string {
  return JSON.stringify(
    InternalServerErrorError$outboundSchema.parse(internalServerErrorError),
  );
}

export function internalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InternalServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const InternalServerError$inboundSchema: z.ZodType<
  InternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => InternalServerErrorError$inboundSchema),
})
  .transform((v) => {
    return new InternalServerError(v);
  });

/** @internal */
export type InternalServerError$Outbound = {
  success: boolean;
  error: InternalServerErrorError$Outbound;
};

/** @internal */
export const InternalServerError$outboundSchema: z.ZodType<
  InternalServerError$Outbound,
  z.ZodTypeDef,
  InternalServerError
> = z.instanceof(InternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => InternalServerErrorError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InternalServerError$ {
  /** @deprecated use `InternalServerError$inboundSchema` instead. */
  export const inboundSchema = InternalServerError$inboundSchema;
  /** @deprecated use `InternalServerError$outboundSchema` instead. */
  export const outboundSchema = InternalServerError$outboundSchema;
  /** @deprecated use `InternalServerError$Outbound` instead. */
  export type Outbound = InternalServerError$Outbound;
}

/** @internal */
export const NotFoundErrorResponse$inboundSchema: z.ZodType<
  NotFoundErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/** @internal */
export type NotFoundErrorResponse$Outbound = {
  code: string;
  message: string;
  details?: any | undefined;
};

/** @internal */
export const NotFoundErrorResponse$outboundSchema: z.ZodType<
  NotFoundErrorResponse$Outbound,
  z.ZodTypeDef,
  NotFoundErrorResponse
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotFoundErrorResponse$ {
  /** @deprecated use `NotFoundErrorResponse$inboundSchema` instead. */
  export const inboundSchema = NotFoundErrorResponse$inboundSchema;
  /** @deprecated use `NotFoundErrorResponse$outboundSchema` instead. */
  export const outboundSchema = NotFoundErrorResponse$outboundSchema;
  /** @deprecated use `NotFoundErrorResponse$Outbound` instead. */
  export type Outbound = NotFoundErrorResponse$Outbound;
}

export function notFoundErrorResponseToJSON(
  notFoundErrorResponse: NotFoundErrorResponse,
): string {
  return JSON.stringify(
    NotFoundErrorResponse$outboundSchema.parse(notFoundErrorResponse),
  );
}

export function notFoundErrorResponseFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotFoundErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundErrorResponse' from JSON`,
  );
}

/** @internal */
export const GetProductsNotFoundError$inboundSchema: z.ZodType<
  GetProductsNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => NotFoundErrorResponse$inboundSchema),
})
  .transform((v) => {
    return new GetProductsNotFoundError(v);
  });

/** @internal */
export type GetProductsNotFoundError$Outbound = {
  success: boolean;
  error: NotFoundErrorResponse$Outbound;
};

/** @internal */
export const GetProductsNotFoundError$outboundSchema: z.ZodType<
  GetProductsNotFoundError$Outbound,
  z.ZodTypeDef,
  GetProductsNotFoundError
> = z.instanceof(GetProductsNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => NotFoundErrorResponse$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsNotFoundError$ {
  /** @deprecated use `GetProductsNotFoundError$inboundSchema` instead. */
  export const inboundSchema = GetProductsNotFoundError$inboundSchema;
  /** @deprecated use `GetProductsNotFoundError$outboundSchema` instead. */
  export const outboundSchema = GetProductsNotFoundError$outboundSchema;
  /** @deprecated use `GetProductsNotFoundError$Outbound` instead. */
  export type Outbound = GetProductsNotFoundError$Outbound;
}

/** @internal */
export const UnauthorizedErrorResponse$inboundSchema: z.ZodType<
  UnauthorizedErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/** @internal */
export type UnauthorizedErrorResponse$Outbound = {
  code: string;
  message: string;
  details?: any | undefined;
};

/** @internal */
export const UnauthorizedErrorResponse$outboundSchema: z.ZodType<
  UnauthorizedErrorResponse$Outbound,
  z.ZodTypeDef,
  UnauthorizedErrorResponse
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedErrorResponse$ {
  /** @deprecated use `UnauthorizedErrorResponse$inboundSchema` instead. */
  export const inboundSchema = UnauthorizedErrorResponse$inboundSchema;
  /** @deprecated use `UnauthorizedErrorResponse$outboundSchema` instead. */
  export const outboundSchema = UnauthorizedErrorResponse$outboundSchema;
  /** @deprecated use `UnauthorizedErrorResponse$Outbound` instead. */
  export type Outbound = UnauthorizedErrorResponse$Outbound;
}

export function unauthorizedErrorResponseToJSON(
  unauthorizedErrorResponse: UnauthorizedErrorResponse,
): string {
  return JSON.stringify(
    UnauthorizedErrorResponse$outboundSchema.parse(unauthorizedErrorResponse),
  );
}

export function unauthorizedErrorResponseFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedErrorResponse' from JSON`,
  );
}

/** @internal */
export const GetProductsUnauthorizedError$inboundSchema: z.ZodType<
  GetProductsUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => UnauthorizedErrorResponse$inboundSchema),
})
  .transform((v) => {
    return new GetProductsUnauthorizedError(v);
  });

/** @internal */
export type GetProductsUnauthorizedError$Outbound = {
  success: boolean;
  error: UnauthorizedErrorResponse$Outbound;
};

/** @internal */
export const GetProductsUnauthorizedError$outboundSchema: z.ZodType<
  GetProductsUnauthorizedError$Outbound,
  z.ZodTypeDef,
  GetProductsUnauthorizedError
> = z.instanceof(GetProductsUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => UnauthorizedErrorResponse$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsUnauthorizedError$ {
  /** @deprecated use `GetProductsUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = GetProductsUnauthorizedError$inboundSchema;
  /** @deprecated use `GetProductsUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema = GetProductsUnauthorizedError$outboundSchema;
  /** @deprecated use `GetProductsUnauthorizedError$Outbound` instead. */
  export type Outbound = GetProductsUnauthorizedError$Outbound;
}

/** @internal */
export const BadRequestErrorResponse$inboundSchema: z.ZodType<
  BadRequestErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/** @internal */
export type BadRequestErrorResponse$Outbound = {
  code: string;
  message: string;
  details?: any | undefined;
};

/** @internal */
export const BadRequestErrorResponse$outboundSchema: z.ZodType<
  BadRequestErrorResponse$Outbound,
  z.ZodTypeDef,
  BadRequestErrorResponse
> = z.object({
  code: z.string(),
  message: z.string(),
  details: z.any().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestErrorResponse$ {
  /** @deprecated use `BadRequestErrorResponse$inboundSchema` instead. */
  export const inboundSchema = BadRequestErrorResponse$inboundSchema;
  /** @deprecated use `BadRequestErrorResponse$outboundSchema` instead. */
  export const outboundSchema = BadRequestErrorResponse$outboundSchema;
  /** @deprecated use `BadRequestErrorResponse$Outbound` instead. */
  export type Outbound = BadRequestErrorResponse$Outbound;
}

export function badRequestErrorResponseToJSON(
  badRequestErrorResponse: BadRequestErrorResponse,
): string {
  return JSON.stringify(
    BadRequestErrorResponse$outboundSchema.parse(badRequestErrorResponse),
  );
}

export function badRequestErrorResponseFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequestErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestErrorResponse' from JSON`,
  );
}

/** @internal */
export const GetProductsBadRequestError$inboundSchema: z.ZodType<
  GetProductsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => BadRequestErrorResponse$inboundSchema),
})
  .transform((v) => {
    return new GetProductsBadRequestError(v);
  });

/** @internal */
export type GetProductsBadRequestError$Outbound = {
  success: boolean;
  error: BadRequestErrorResponse$Outbound;
};

/** @internal */
export const GetProductsBadRequestError$outboundSchema: z.ZodType<
  GetProductsBadRequestError$Outbound,
  z.ZodTypeDef,
  GetProductsBadRequestError
> = z.instanceof(GetProductsBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => BadRequestErrorResponse$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsBadRequestError$ {
  /** @deprecated use `GetProductsBadRequestError$inboundSchema` instead. */
  export const inboundSchema = GetProductsBadRequestError$inboundSchema;
  /** @deprecated use `GetProductsBadRequestError$outboundSchema` instead. */
  export const outboundSchema = GetProductsBadRequestError$outboundSchema;
  /** @deprecated use `GetProductsBadRequestError$Outbound` instead. */
  export type Outbound = GetProductsBadRequestError$Outbound;
}

/** @internal */
export const UnprocessableEntityErrorResponse$inboundSchema: z.ZodType<
  UnprocessableEntityErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => Issue$inboundSchema)),
  name: z.string(),
});

/** @internal */
export type UnprocessableEntityErrorResponse$Outbound = {
  issues: Array<Issue$Outbound>;
  name: string;
};

/** @internal */
export const UnprocessableEntityErrorResponse$outboundSchema: z.ZodType<
  UnprocessableEntityErrorResponse$Outbound,
  z.ZodTypeDef,
  UnprocessableEntityErrorResponse
> = z.object({
  issues: z.array(z.lazy(() => Issue$outboundSchema)),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnprocessableEntityErrorResponse$ {
  /** @deprecated use `UnprocessableEntityErrorResponse$inboundSchema` instead. */
  export const inboundSchema = UnprocessableEntityErrorResponse$inboundSchema;
  /** @deprecated use `UnprocessableEntityErrorResponse$outboundSchema` instead. */
  export const outboundSchema = UnprocessableEntityErrorResponse$outboundSchema;
  /** @deprecated use `UnprocessableEntityErrorResponse$Outbound` instead. */
  export type Outbound = UnprocessableEntityErrorResponse$Outbound;
}

export function unprocessableEntityErrorResponseToJSON(
  unprocessableEntityErrorResponse: UnprocessableEntityErrorResponse,
): string {
  return JSON.stringify(
    UnprocessableEntityErrorResponse$outboundSchema.parse(
      unprocessableEntityErrorResponse,
    ),
  );
}

export function unprocessableEntityErrorResponseFromJSON(
  jsonString: string,
): SafeParseResult<UnprocessableEntityErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnprocessableEntityErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnprocessableEntityErrorResponse' from JSON`,
  );
}

/** @internal */
export const ResponseBodyError2$inboundSchema: z.ZodType<
  ResponseBodyError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => UnprocessableEntityErrorResponse$inboundSchema),
})
  .transform((v) => {
    return new ResponseBodyError2(v);
  });

/** @internal */
export type ResponseBodyError2$Outbound = {
  success: boolean;
  error: UnprocessableEntityErrorResponse$Outbound;
};

/** @internal */
export const ResponseBodyError2$outboundSchema: z.ZodType<
  ResponseBodyError2$Outbound,
  z.ZodTypeDef,
  ResponseBodyError2
> = z.instanceof(ResponseBodyError2)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => UnprocessableEntityErrorResponse$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyError2$ {
  /** @deprecated use `ResponseBodyError2$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyError2$inboundSchema;
  /** @deprecated use `ResponseBodyError2$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyError2$outboundSchema;
  /** @deprecated use `ResponseBodyError2$Outbound` instead. */
  export type Outbound = ResponseBodyError2$Outbound;
}

/** @internal */
export const PatchProductsIdPath1$inboundSchema: z.ZodType<
  PatchProductsIdPath1,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);

/** @internal */
export type PatchProductsIdPath1$Outbound = string | number;

/** @internal */
export const PatchProductsIdPath1$outboundSchema: z.ZodType<
  PatchProductsIdPath1$Outbound,
  z.ZodTypeDef,
  PatchProductsIdPath1
> = z.union([z.string(), z.number()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdPath1$ {
  /** @deprecated use `PatchProductsIdPath1$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdPath1$inboundSchema;
  /** @deprecated use `PatchProductsIdPath1$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdPath1$outboundSchema;
  /** @deprecated use `PatchProductsIdPath1$Outbound` instead. */
  export type Outbound = PatchProductsIdPath1$Outbound;
}

export function patchProductsIdPath1ToJSON(
  patchProductsIdPath1: PatchProductsIdPath1,
): string {
  return JSON.stringify(
    PatchProductsIdPath1$outboundSchema.parse(patchProductsIdPath1),
  );
}

export function patchProductsIdPath1FromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdPath1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdPath1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdPath1' from JSON`,
  );
}

/** @internal */
export const Issue$inboundSchema: z.ZodType<Issue, z.ZodTypeDef, unknown> = z
  .object({
    code: z.string(),
    path: z.array(z.union([z.string(), z.number()])),
    message: z.string().optional(),
  });

/** @internal */
export type Issue$Outbound = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

/** @internal */
export const Issue$outboundSchema: z.ZodType<
  Issue$Outbound,
  z.ZodTypeDef,
  Issue
> = z.object({
  code: z.string(),
  path: z.array(z.union([z.string(), z.number()])),
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Issue$ {
  /** @deprecated use `Issue$inboundSchema` instead. */
  export const inboundSchema = Issue$inboundSchema;
  /** @deprecated use `Issue$outboundSchema` instead. */
  export const outboundSchema = Issue$outboundSchema;
  /** @deprecated use `Issue$Outbound` instead. */
  export type Outbound = Issue$Outbound;
}

export function issueToJSON(issue: Issue): string {
  return JSON.stringify(Issue$outboundSchema.parse(issue));
}

export function issueFromJSON(
  jsonString: string,
): SafeParseResult<Issue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Issue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Issue' from JSON`,
  );
}

/** @internal */
export const ResponseBodyUnprocessableEntityError$inboundSchema: z.ZodType<
  ResponseBodyUnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => Issue$inboundSchema)),
  name: z.string(),
});

/** @internal */
export type ResponseBodyUnprocessableEntityError$Outbound = {
  issues: Array<Issue$Outbound>;
  name: string;
};

/** @internal */
export const ResponseBodyUnprocessableEntityError$outboundSchema: z.ZodType<
  ResponseBodyUnprocessableEntityError$Outbound,
  z.ZodTypeDef,
  ResponseBodyUnprocessableEntityError
> = z.object({
  issues: z.array(z.lazy(() => Issue$outboundSchema)),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyUnprocessableEntityError$ {
  /** @deprecated use `ResponseBodyUnprocessableEntityError$inboundSchema` instead. */
  export const inboundSchema =
    ResponseBodyUnprocessableEntityError$inboundSchema;
  /** @deprecated use `ResponseBodyUnprocessableEntityError$outboundSchema` instead. */
  export const outboundSchema =
    ResponseBodyUnprocessableEntityError$outboundSchema;
  /** @deprecated use `ResponseBodyUnprocessableEntityError$Outbound` instead. */
  export type Outbound = ResponseBodyUnprocessableEntityError$Outbound;
}

export function responseBodyUnprocessableEntityErrorToJSON(
  responseBodyUnprocessableEntityError: ResponseBodyUnprocessableEntityError,
): string {
  return JSON.stringify(
    ResponseBodyUnprocessableEntityError$outboundSchema.parse(
      responseBodyUnprocessableEntityError,
    ),
  );
}

export function responseBodyUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyUnprocessableEntityError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResponseBodyUnprocessableEntityError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const ResponseBodyError1$inboundSchema: z.ZodType<
  ResponseBodyError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => ResponseBodyUnprocessableEntityError$inboundSchema),
})
  .transform((v) => {
    return new ResponseBodyError1(v);
  });

/** @internal */
export type ResponseBodyError1$Outbound = {
  success: boolean;
  error: ResponseBodyUnprocessableEntityError$Outbound;
};

/** @internal */
export const ResponseBodyError1$outboundSchema: z.ZodType<
  ResponseBodyError1$Outbound,
  z.ZodTypeDef,
  ResponseBodyError1
> = z.instanceof(ResponseBodyError1)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => ResponseBodyUnprocessableEntityError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyError1$ {
  /** @deprecated use `ResponseBodyError1$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyError1$inboundSchema;
  /** @deprecated use `ResponseBodyError1$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyError1$outboundSchema;
  /** @deprecated use `ResponseBodyError1$Outbound` instead. */
  export type Outbound = ResponseBodyError1$Outbound;
}

/** @internal */
export const PatchProductsIdUnprocessableEntity$inboundSchema: z.ZodType<
  PatchProductsIdUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ResponseBodyError1$inboundSchema),
  z.lazy(() => ResponseBodyError2$inboundSchema),
]);

/** @internal */
export type PatchProductsIdUnprocessableEntity$Outbound =
  | ResponseBodyError1$Outbound
  | ResponseBodyError2$Outbound;

/** @internal */
export const PatchProductsIdUnprocessableEntity$outboundSchema: z.ZodType<
  PatchProductsIdUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  PatchProductsIdUnprocessableEntity
> = z.union([
  z.lazy(() => ResponseBodyError1$outboundSchema),
  z.lazy(() => ResponseBodyError2$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdUnprocessableEntity$ {
  /** @deprecated use `PatchProductsIdUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdUnprocessableEntity$inboundSchema;
  /** @deprecated use `PatchProductsIdUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema =
    PatchProductsIdUnprocessableEntity$outboundSchema;
  /** @deprecated use `PatchProductsIdUnprocessableEntity$Outbound` instead. */
  export type Outbound = PatchProductsIdUnprocessableEntity$Outbound;
}

export function patchProductsIdUnprocessableEntityToJSON(
  patchProductsIdUnprocessableEntity: PatchProductsIdUnprocessableEntity,
): string {
  return JSON.stringify(
    PatchProductsIdUnprocessableEntity$outboundSchema.parse(
      patchProductsIdUnprocessableEntity,
    ),
  );
}

export function patchProductsIdUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchProductsIdUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdUnprocessableEntity' from JSON`,
  );
}

/** @internal */
export const DeleteProductsIdUnprocessableEntityError$inboundSchema: z.ZodType<
  DeleteProductsIdUnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.lazy(() => UnprocessableEntityErrorResponse$inboundSchema),
})
  .transform((v) => {
    return new DeleteProductsIdUnprocessableEntityError(v);
  });

/** @internal */
export type DeleteProductsIdUnprocessableEntityError$Outbound = {
  success: boolean;
  error: UnprocessableEntityErrorResponse$Outbound;
};

/** @internal */
export const DeleteProductsIdUnprocessableEntityError$outboundSchema: z.ZodType<
  DeleteProductsIdUnprocessableEntityError$Outbound,
  z.ZodTypeDef,
  DeleteProductsIdUnprocessableEntityError
> = z.instanceof(DeleteProductsIdUnprocessableEntityError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.lazy(() => UnprocessableEntityErrorResponse$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteProductsIdUnprocessableEntityError$ {
  /** @deprecated use `DeleteProductsIdUnprocessableEntityError$inboundSchema` instead. */
  export const inboundSchema =
    DeleteProductsIdUnprocessableEntityError$inboundSchema;
  /** @deprecated use `DeleteProductsIdUnprocessableEntityError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteProductsIdUnprocessableEntityError$outboundSchema;
  /** @deprecated use `DeleteProductsIdUnprocessableEntityError$Outbound` instead. */
  export type Outbound = DeleteProductsIdUnprocessableEntityError$Outbound;
}

/** @internal */
export const PatchCustomersIdUnprocessableEntity$inboundSchema: z.ZodType<
  PatchCustomersIdUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ResponseBodyError1$inboundSchema),
  z.lazy(() => ResponseBodyError2$inboundSchema),
]);

/** @internal */
export type PatchCustomersIdUnprocessableEntity$Outbound =
  | ResponseBodyError1$Outbound
  | ResponseBodyError2$Outbound;

/** @internal */
export const PatchCustomersIdUnprocessableEntity$outboundSchema: z.ZodType<
  PatchCustomersIdUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdUnprocessableEntity
> = z.union([
  z.lazy(() => ResponseBodyError1$outboundSchema),
  z.lazy(() => ResponseBodyError2$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdUnprocessableEntity$ {
  /** @deprecated use `PatchCustomersIdUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema =
    PatchCustomersIdUnprocessableEntity$inboundSchema;
  /** @deprecated use `PatchCustomersIdUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema =
    PatchCustomersIdUnprocessableEntity$outboundSchema;
  /** @deprecated use `PatchCustomersIdUnprocessableEntity$Outbound` instead. */
  export type Outbound = PatchCustomersIdUnprocessableEntity$Outbound;
}

export function patchCustomersIdUnprocessableEntityToJSON(
  patchCustomersIdUnprocessableEntity: PatchCustomersIdUnprocessableEntity,
): string {
  return JSON.stringify(
    PatchCustomersIdUnprocessableEntity$outboundSchema.parse(
      patchCustomersIdUnprocessableEntity,
    ),
  );
}

export function patchCustomersIdUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchCustomersIdUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdUnprocessableEntity' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdUnprocessableEntity$inboundSchema: z.ZodType<
  PatchTransactionsIdUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ResponseBodyError1$inboundSchema),
  z.lazy(() => ResponseBodyError2$inboundSchema),
]);

/** @internal */
export type PatchTransactionsIdUnprocessableEntity$Outbound =
  | ResponseBodyError1$Outbound
  | ResponseBodyError2$Outbound;

/** @internal */
export const PatchTransactionsIdUnprocessableEntity$outboundSchema: z.ZodType<
  PatchTransactionsIdUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdUnprocessableEntity
> = z.union([
  z.lazy(() => ResponseBodyError1$outboundSchema),
  z.lazy(() => ResponseBodyError2$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdUnprocessableEntity$ {
  /** @deprecated use `PatchTransactionsIdUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema =
    PatchTransactionsIdUnprocessableEntity$inboundSchema;
  /** @deprecated use `PatchTransactionsIdUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdUnprocessableEntity$outboundSchema;
  /** @deprecated use `PatchTransactionsIdUnprocessableEntity$Outbound` instead. */
  export type Outbound = PatchTransactionsIdUnprocessableEntity$Outbound;
}

export function patchTransactionsIdUnprocessableEntityToJSON(
  patchTransactionsIdUnprocessableEntity:
    PatchTransactionsIdUnprocessableEntity,
): string {
  return JSON.stringify(
    PatchTransactionsIdUnprocessableEntity$outboundSchema.parse(
      patchTransactionsIdUnprocessableEntity,
    ),
  );
}

export function patchTransactionsIdUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchTransactionsIdUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdUnprocessableEntity' from JSON`,
  );
}
