/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { MpesaFlowError } from "./mpesaflowerror.js";

export type TooManyRequestsErrorData = {
  error: models.TooManyRequestsErrorError;
};

export class TooManyRequestsError extends MpesaFlowError {
  error: models.TooManyRequestsErrorError;

  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "TooManyRequestsError";
  }
}

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodType<
  TooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.TooManyRequestsErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type TooManyRequestsError$Outbound = {
  error: models.TooManyRequestsErrorError$Outbound;
};

/** @internal */
export const TooManyRequestsError$outboundSchema: z.ZodType<
  TooManyRequestsError$Outbound,
  z.ZodTypeDef,
  TooManyRequestsError
> = z.instanceof(TooManyRequestsError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => models.TooManyRequestsErrorError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TooManyRequestsError$ {
  /** @deprecated use `TooManyRequestsError$inboundSchema` instead. */
  export const inboundSchema = TooManyRequestsError$inboundSchema;
  /** @deprecated use `TooManyRequestsError$outboundSchema` instead. */
  export const outboundSchema = TooManyRequestsError$outboundSchema;
  /** @deprecated use `TooManyRequestsError$Outbound` instead. */
  export type Outbound = TooManyRequestsError$Outbound;
}
