/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreate } from "../../funcs/customersCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostCustomersRequest$inboundSchema,
};

export const tool$customersCreate: ToolDefinition<typeof args> = {
  name: "customers-create",
  description: `Create a customer

Create a customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
