/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { darajaPaymentMpesaPay } from "../../funcs/darajaPaymentMpesaPay.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostPayMpesaRequest$inboundSchema,
};

export const tool$darajaPaymentMpesaPay: ToolDefinition<typeof args> = {
  name: "daraja-payment-mpesa-pay",
  description: `Initiate M-Pesa payment

Initiate M-Pesa payment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await darajaPaymentMpesaPay(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
