/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsDelete } from "../../funcs/productsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteProductsIdRequest$inboundSchema,
};

export const tool$productsDelete: ToolDefinition<typeof args> = {
  name: "products-delete",
  description: `Remove a product

Remove a product`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await productsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
