/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsList } from "../../funcs/productsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetProductsRequest$inboundSchema,
};

export const tool$productsList: ToolDefinition<typeof args> = {
  name: "products-list",
  description: `List of all products

List of all products`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await productsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
