/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { MpesaFlowCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$customersCreate } from "./tools/customersCreate.js";
import { tool$customersDelete } from "./tools/customersDelete.js";
import { tool$customersGet } from "./tools/customersGet.js";
import { tool$customersList } from "./tools/customersList.js";
import { tool$customersUpdate } from "./tools/customersUpdate.js";
import { tool$darajaPaymentMpesaPay } from "./tools/darajaPaymentMpesaPay.js";
import { tool$productsCreate } from "./tools/productsCreate.js";
import { tool$productsDelete } from "./tools/productsDelete.js";
import { tool$productsGet } from "./tools/productsGet.js";
import { tool$productsList } from "./tools/productsList.js";
import { tool$productsUpdate } from "./tools/productsUpdate.js";
import { tool$transactionsCreate } from "./tools/transactionsCreate.js";
import { tool$transactionsDelete } from "./tools/transactionsDelete.js";
import { tool$transactionsGet } from "./tools/transactionsGet.js";
import { tool$transactionsList } from "./tools/transactionsList.js";
import { tool$transactionsUpdate } from "./tools/transactionsUpdate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  bearer?: SDKOptions["bearer"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "MpesaFlow",
    version: "0.1.3",
  });

  const client = new MpesaFlowCore({
    bearer: deps.bearer,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$productsList);
  tool(tool$productsCreate);
  tool(tool$productsGet);
  tool(tool$productsUpdate);
  tool(tool$productsDelete);
  tool(tool$customersList);
  tool(tool$customersCreate);
  tool(tool$customersGet);
  tool(tool$customersUpdate);
  tool(tool$customersDelete);
  tool(tool$transactionsList);
  tool(tool$transactionsCreate);
  tool(tool$transactionsGet);
  tool(tool$transactionsUpdate);
  tool(tool$transactionsDelete);
  tool(tool$darajaPaymentMpesaPay);

  return server;
}
