/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreate } from "../funcs/customersCreate.js";
import { customersDelete } from "../funcs/customersDelete.js";
import { customersGet } from "../funcs/customersGet.js";
import { customersList } from "../funcs/customersList.js";
import { customersUpdate } from "../funcs/customersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Customers extends ClientSDK {
  /**
   * List of all customers
   *
   * @remarks
   * List of all customers
   */
  async list(
    request: operations.GetCustomersRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomersResponse> {
    return unwrapAsync(customersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a customer
   */
  async create(
    request: operations.PostCustomersRequest,
    options?: RequestOptions,
  ): Promise<operations.PostCustomersResponse> {
    return unwrapAsync(customersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer
   *
   * @remarks
   * Get a customer
   */
  async get(
    request: operations.GetCustomersIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomersIdResponse> {
    return unwrapAsync(customersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer
   *
   * @remarks
   * Update a customer
   */
  async update(
    request: operations.PatchCustomersIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchCustomersIdResponse> {
    return unwrapAsync(customersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a customer
   *
   * @remarks
   * Remove a customer
   */
  async delete(
    request: operations.DeleteCustomersIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(customersDelete(
      this,
      request,
      options,
    ));
  }
}
