/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreate } from "../funcs/customersCreate.js";
import { customersDelete } from "../funcs/customersDelete.js";
import { customersGetOne } from "../funcs/customersGetOne.js";
import { customersList } from "../funcs/customersList.js";
import { customersUpdate } from "../funcs/customersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Customers extends ClientSDK {
  /**
   * List all customers
   *
   * @remarks
   * Get a list of all customers in the business
   */
  async list(
    request?: operations.ListCustomersRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListCustomersResponse, { cursor: string }>
  > {
    return unwrapResultIterator(customersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a customer in the business
   */
  async create(
    request: operations.CreateRequest,
    options?: RequestOptions,
  ): Promise<models.CustomerResponse> {
    return unwrapAsync(customersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer
   *
   * @remarks
   * Get a customer by their ID in the business
   */
  async getOne(
    request: operations.GetCustomerRequest,
    options?: RequestOptions,
  ): Promise<models.CustomerResponse> {
    return unwrapAsync(customersGetOne(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer
   *
   * @remarks
   * Update a customer in the business
   */
  async update(
    request: operations.UpdateRequest,
    options?: RequestOptions,
  ): Promise<models.CustomerResponse> {
    return unwrapAsync(customersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a customer
   *
   * @remarks
   * Delete a customer by their ID in the business
   */
  async delete(
    request: operations.DeleteRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(customersDelete(
      this,
      request,
      options,
    ));
  }
}
