/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { darajaPaymentMpesaPay } from "../funcs/darajaPaymentMpesaPay.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DarajaPayment extends ClientSDK {
  /**
   * Initiate M-Pesa payment
   *
   * @remarks
   * Initiate M-Pesa payment
   */
  async mpesaPay(
    request: operations.PostPayMpesaRequest,
    options?: RequestOptions,
  ): Promise<operations.PostPayMpesaResponse> {
    return unwrapAsync(darajaPaymentMpesaPay(
      this,
      request,
      options,
    ));
  }
}
