/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expressPay } from "../funcs/expressPay.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Express extends ClientSDK {
  /**
   * Simulate Daraja express payment
   *
   * @remarks
   * Simulate Daraja express payment
   */
  async pay(
    request: operations.ExpressRequest,
    options?: RequestOptions,
  ): Promise<operations.ExpressResponse> {
    return unwrapAsync(expressPay(
      this,
      request,
      options,
    ));
  }
}
