/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsCreate } from "../funcs/productsCreate.js";
import { productsDelete } from "../funcs/productsDelete.js";
import { productsGet } from "../funcs/productsGet.js";
import { productsList } from "../funcs/productsList.js";
import { productsUpdate } from "../funcs/productsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Products extends ClientSDK {
  /**
   * List of all products
   *
   * @remarks
   * List of all products
   */
  async list(
    request: operations.GetProductsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProductsResponse> {
    return unwrapAsync(productsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a product
   *
   * @remarks
   * Create a product
   */
  async create(
    request: operations.PostProductsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostProductsResponse> {
    return unwrapAsync(productsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a product
   *
   * @remarks
   * Get a product
   */
  async get(
    request: operations.GetProductsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProductsIdResponse> {
    return unwrapAsync(productsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a product
   *
   * @remarks
   * Update a product
   */
  async update(
    request: operations.PatchProductsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchProductsIdResponse> {
    return unwrapAsync(productsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a product
   *
   * @remarks
   * Remove a product
   */
  async delete(
    request: operations.DeleteProductsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(productsDelete(
      this,
      request,
      options,
    ));
  }
}
