/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Customers } from "./customers.js";
import { DarajaPayment } from "./darajapayment.js";
import { Products } from "./products.js";
import { Transactions } from "./transactions.js";

export class MpesaFlow extends ClientSDK {
  private _products?: Products;
  get products(): Products {
    return (this._products ??= new Products(this._options));
  }

  private _customers?: Customers;
  get customers(): Customers {
    return (this._customers ??= new Customers(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _darajaPayment?: DarajaPayment;
  get darajaPayment(): DarajaPayment {
    return (this._darajaPayment ??= new DarajaPayment(this._options));
  }
}
