/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsCreate } from "../funcs/transactionsCreate.js";
import { transactionsDelete } from "../funcs/transactionsDelete.js";
import { transactionsGet } from "../funcs/transactionsGet.js";
import { transactionsList } from "../funcs/transactionsList.js";
import { transactionsUpdate } from "../funcs/transactionsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * List of all transactions
   *
   * @remarks
   * List of all transactions
   */
  async list(
    request: operations.GetTransactionsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTransactionsResponse> {
    return unwrapAsync(transactionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a transaction
   *
   * @remarks
   * Create a transaction
   */
  async create(
    request: operations.PostTransactionsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostTransactionsResponse> {
    return unwrapAsync(transactionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a transaction
   *
   * @remarks
   * Get a transaction
   */
  async get(
    request: operations.GetTransactionsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTransactionsIdResponse> {
    return unwrapAsync(transactionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a transaction
   *
   * @remarks
   * Update a transaction
   */
  async update(
    request: operations.PatchTransactionsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchTransactionsIdResponse> {
    return unwrapAsync(transactionsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a transaction
   *
   * @remarks
   * Remove a transaction
   */
  async delete(
    request: operations.DeleteTransactionsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(transactionsDelete(
      this,
      request,
      options,
    ));
  }
}
