/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @mpesaflow/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx customersList.ts
 */

import { MpesaFlow } from "@mpesaflow/sdk";

const mpesaFlow = new MpesaFlow({
  token: "MPESAFLOW_API_KEY",
});

async function main() {
  const result = await mpesaFlow.list({
    q: "John Doe",
    cursor: "eyJpZCI6IjEyMyJ9",
    start: "2024-04-01T00:00:00.000Z",
    end: "2024-04-30T23:59:59.999Z",
  });

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
