/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteProductsIdRequest = {
  id: string;
};

/** @internal */
export const DeleteProductsIdRequest$inboundSchema: z.ZodType<
  DeleteProductsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteProductsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteProductsIdRequest$outboundSchema: z.ZodType<
  DeleteProductsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteProductsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteProductsIdRequest$ {
  /** @deprecated use `DeleteProductsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteProductsIdRequest$inboundSchema;
  /** @deprecated use `DeleteProductsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteProductsIdRequest$outboundSchema;
  /** @deprecated use `DeleteProductsIdRequest$Outbound` instead. */
  export type Outbound = DeleteProductsIdRequest$Outbound;
}

export function deleteProductsIdRequestToJSON(
  deleteProductsIdRequest: DeleteProductsIdRequest,
): string {
  return JSON.stringify(
    DeleteProductsIdRequest$outboundSchema.parse(deleteProductsIdRequest),
  );
}

export function deleteProductsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteProductsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteProductsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteProductsIdRequest' from JSON`,
  );
}
