/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTransactionsIdRequest = {
  id: string;
};

/** @internal */
export const DeleteTransactionsIdRequest$inboundSchema: z.ZodType<
  DeleteTransactionsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteTransactionsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTransactionsIdRequest$outboundSchema: z.ZodType<
  DeleteTransactionsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteTransactionsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTransactionsIdRequest$ {
  /** @deprecated use `DeleteTransactionsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteTransactionsIdRequest$inboundSchema;
  /** @deprecated use `DeleteTransactionsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteTransactionsIdRequest$outboundSchema;
  /** @deprecated use `DeleteTransactionsIdRequest$Outbound` instead. */
  export type Outbound = DeleteTransactionsIdRequest$Outbound;
}

export function deleteTransactionsIdRequestToJSON(
  deleteTransactionsIdRequest: DeleteTransactionsIdRequest,
): string {
  return JSON.stringify(
    DeleteTransactionsIdRequest$outboundSchema.parse(
      deleteTransactionsIdRequest,
    ),
  );
}

export function deleteTransactionsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTransactionsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTransactionsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTransactionsIdRequest' from JSON`,
  );
}
