/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteCustomersIdRequest = {
  id: string;
};

/** @internal */
export const DeleteCustomersIdRequest$inboundSchema: z.ZodType<
  DeleteCustomersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteCustomersIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCustomersIdRequest$outboundSchema: z.ZodType<
  DeleteCustomersIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteCustomersIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCustomersIdRequest$ {
  /** @deprecated use `DeleteCustomersIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteCustomersIdRequest$inboundSchema;
  /** @deprecated use `DeleteCustomersIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteCustomersIdRequest$outboundSchema;
  /** @deprecated use `DeleteCustomersIdRequest$Outbound` instead. */
  export type Outbound = DeleteCustomersIdRequest$Outbound;
}

export function deleteCustomersIdRequestToJSON(
  deleteCustomersIdRequest: DeleteCustomersIdRequest,
): string {
  return JSON.stringify(
    DeleteCustomersIdRequest$outboundSchema.parse(deleteCustomersIdRequest),
  );
}

export function deleteCustomersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCustomersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCustomersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCustomersIdRequest' from JSON`,
  );
}
