/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCustomersIdRequest = {
  id: string;
};

export type GetCustomersIdMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetCustomersIdData = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

/**
 * Get One Customer
 */
export type GetCustomersIdResponse = {
  success: boolean;
  data: GetCustomersIdData;
};

/** @internal */
export const GetCustomersIdRequest$inboundSchema: z.ZodType<
  GetCustomersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetCustomersIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomersIdRequest$outboundSchema: z.ZodType<
  GetCustomersIdRequest$Outbound,
  z.ZodTypeDef,
  GetCustomersIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersIdRequest$ {
  /** @deprecated use `GetCustomersIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetCustomersIdRequest$inboundSchema;
  /** @deprecated use `GetCustomersIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetCustomersIdRequest$outboundSchema;
  /** @deprecated use `GetCustomersIdRequest$Outbound` instead. */
  export type Outbound = GetCustomersIdRequest$Outbound;
}

export function getCustomersIdRequestToJSON(
  getCustomersIdRequest: GetCustomersIdRequest,
): string {
  return JSON.stringify(
    GetCustomersIdRequest$outboundSchema.parse(getCustomersIdRequest),
  );
}

export function getCustomersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersIdRequest' from JSON`,
  );
}

/** @internal */
export const GetCustomersIdMetadata$inboundSchema: z.ZodType<
  GetCustomersIdMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetCustomersIdMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetCustomersIdMetadata$outboundSchema: z.ZodType<
  GetCustomersIdMetadata$Outbound,
  z.ZodTypeDef,
  GetCustomersIdMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersIdMetadata$ {
  /** @deprecated use `GetCustomersIdMetadata$inboundSchema` instead. */
  export const inboundSchema = GetCustomersIdMetadata$inboundSchema;
  /** @deprecated use `GetCustomersIdMetadata$outboundSchema` instead. */
  export const outboundSchema = GetCustomersIdMetadata$outboundSchema;
  /** @deprecated use `GetCustomersIdMetadata$Outbound` instead. */
  export type Outbound = GetCustomersIdMetadata$Outbound;
}

export function getCustomersIdMetadataToJSON(
  getCustomersIdMetadata: GetCustomersIdMetadata,
): string {
  return JSON.stringify(
    GetCustomersIdMetadata$outboundSchema.parse(getCustomersIdMetadata),
  );
}

export function getCustomersIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersIdMetadata' from JSON`,
  );
}

/** @internal */
export const GetCustomersIdData$inboundSchema: z.ZodType<
  GetCustomersIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/** @internal */
export type GetCustomersIdData$Outbound = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

/** @internal */
export const GetCustomersIdData$outboundSchema: z.ZodType<
  GetCustomersIdData$Outbound,
  z.ZodTypeDef,
  GetCustomersIdData
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersIdData$ {
  /** @deprecated use `GetCustomersIdData$inboundSchema` instead. */
  export const inboundSchema = GetCustomersIdData$inboundSchema;
  /** @deprecated use `GetCustomersIdData$outboundSchema` instead. */
  export const outboundSchema = GetCustomersIdData$outboundSchema;
  /** @deprecated use `GetCustomersIdData$Outbound` instead. */
  export type Outbound = GetCustomersIdData$Outbound;
}

export function getCustomersIdDataToJSON(
  getCustomersIdData: GetCustomersIdData,
): string {
  return JSON.stringify(
    GetCustomersIdData$outboundSchema.parse(getCustomersIdData),
  );
}

export function getCustomersIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersIdData' from JSON`,
  );
}

/** @internal */
export const GetCustomersIdResponse$inboundSchema: z.ZodType<
  GetCustomersIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetCustomersIdData$inboundSchema),
});

/** @internal */
export type GetCustomersIdResponse$Outbound = {
  success: boolean;
  data: GetCustomersIdData$Outbound;
};

/** @internal */
export const GetCustomersIdResponse$outboundSchema: z.ZodType<
  GetCustomersIdResponse$Outbound,
  z.ZodTypeDef,
  GetCustomersIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetCustomersIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersIdResponse$ {
  /** @deprecated use `GetCustomersIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetCustomersIdResponse$inboundSchema;
  /** @deprecated use `GetCustomersIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetCustomersIdResponse$outboundSchema;
  /** @deprecated use `GetCustomersIdResponse$Outbound` instead. */
  export type Outbound = GetCustomersIdResponse$Outbound;
}

export function getCustomersIdResponseToJSON(
  getCustomersIdResponse: GetCustomersIdResponse,
): string {
  return JSON.stringify(
    GetCustomersIdResponse$outboundSchema.parse(getCustomersIdResponse),
  );
}

export function getCustomersIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersIdResponse' from JSON`,
  );
}
