/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetCustomersSortField = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Name: "name",
  Balance: "balance",
  Email: "email",
} as const;
export type GetCustomersSortField = ClosedEnum<typeof GetCustomersSortField>;

export const GetCustomersSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCustomersSortOrder = ClosedEnum<typeof GetCustomersSortOrder>;

export type GetCustomersRequest = {
  query?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortField?: GetCustomersSortField | undefined;
  sortOrder?: GetCustomersSortOrder | undefined;
};

export type GetCustomersMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetCustomersData = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

export type GetCustomersPagination = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/**
 * List of all customers
 */
export type GetCustomersResponse = {
  data: Array<GetCustomersData>;
  pagination: GetCustomersPagination;
};

/** @internal */
export const GetCustomersSortField$inboundSchema: z.ZodNativeEnum<
  typeof GetCustomersSortField
> = z.nativeEnum(GetCustomersSortField);

/** @internal */
export const GetCustomersSortField$outboundSchema: z.ZodNativeEnum<
  typeof GetCustomersSortField
> = GetCustomersSortField$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersSortField$ {
  /** @deprecated use `GetCustomersSortField$inboundSchema` instead. */
  export const inboundSchema = GetCustomersSortField$inboundSchema;
  /** @deprecated use `GetCustomersSortField$outboundSchema` instead. */
  export const outboundSchema = GetCustomersSortField$outboundSchema;
}

/** @internal */
export const GetCustomersSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof GetCustomersSortOrder
> = z.nativeEnum(GetCustomersSortOrder);

/** @internal */
export const GetCustomersSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetCustomersSortOrder
> = GetCustomersSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersSortOrder$ {
  /** @deprecated use `GetCustomersSortOrder$inboundSchema` instead. */
  export const inboundSchema = GetCustomersSortOrder$inboundSchema;
  /** @deprecated use `GetCustomersSortOrder$outboundSchema` instead. */
  export const outboundSchema = GetCustomersSortOrder$outboundSchema;
}

/** @internal */
export const GetCustomersRequest$inboundSchema: z.ZodType<
  GetCustomersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string().optional(),
  page: z.number().default(1),
  limit: z.number().default(10),
  sort_field: GetCustomersSortField$inboundSchema.default("createdAt"),
  sort_order: GetCustomersSortOrder$inboundSchema.default("desc"),
}).transform((v) => {
  return remap$(v, {
    "sort_field": "sortField",
    "sort_order": "sortOrder",
  });
});

/** @internal */
export type GetCustomersRequest$Outbound = {
  query?: string | undefined;
  page: number;
  limit: number;
  sort_field: string;
  sort_order: string;
};

/** @internal */
export const GetCustomersRequest$outboundSchema: z.ZodType<
  GetCustomersRequest$Outbound,
  z.ZodTypeDef,
  GetCustomersRequest
> = z.object({
  query: z.string().optional(),
  page: z.number().default(1),
  limit: z.number().default(10),
  sortField: GetCustomersSortField$outboundSchema.default("createdAt"),
  sortOrder: GetCustomersSortOrder$outboundSchema.default("desc"),
}).transform((v) => {
  return remap$(v, {
    sortField: "sort_field",
    sortOrder: "sort_order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersRequest$ {
  /** @deprecated use `GetCustomersRequest$inboundSchema` instead. */
  export const inboundSchema = GetCustomersRequest$inboundSchema;
  /** @deprecated use `GetCustomersRequest$outboundSchema` instead. */
  export const outboundSchema = GetCustomersRequest$outboundSchema;
  /** @deprecated use `GetCustomersRequest$Outbound` instead. */
  export type Outbound = GetCustomersRequest$Outbound;
}

export function getCustomersRequestToJSON(
  getCustomersRequest: GetCustomersRequest,
): string {
  return JSON.stringify(
    GetCustomersRequest$outboundSchema.parse(getCustomersRequest),
  );
}

export function getCustomersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersRequest' from JSON`,
  );
}

/** @internal */
export const GetCustomersMetadata$inboundSchema: z.ZodType<
  GetCustomersMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetCustomersMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetCustomersMetadata$outboundSchema: z.ZodType<
  GetCustomersMetadata$Outbound,
  z.ZodTypeDef,
  GetCustomersMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersMetadata$ {
  /** @deprecated use `GetCustomersMetadata$inboundSchema` instead. */
  export const inboundSchema = GetCustomersMetadata$inboundSchema;
  /** @deprecated use `GetCustomersMetadata$outboundSchema` instead. */
  export const outboundSchema = GetCustomersMetadata$outboundSchema;
  /** @deprecated use `GetCustomersMetadata$Outbound` instead. */
  export type Outbound = GetCustomersMetadata$Outbound;
}

export function getCustomersMetadataToJSON(
  getCustomersMetadata: GetCustomersMetadata,
): string {
  return JSON.stringify(
    GetCustomersMetadata$outboundSchema.parse(getCustomersMetadata),
  );
}

export function getCustomersMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersMetadata' from JSON`,
  );
}

/** @internal */
export const GetCustomersData$inboundSchema: z.ZodType<
  GetCustomersData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/** @internal */
export type GetCustomersData$Outbound = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

/** @internal */
export const GetCustomersData$outboundSchema: z.ZodType<
  GetCustomersData$Outbound,
  z.ZodTypeDef,
  GetCustomersData
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersData$ {
  /** @deprecated use `GetCustomersData$inboundSchema` instead. */
  export const inboundSchema = GetCustomersData$inboundSchema;
  /** @deprecated use `GetCustomersData$outboundSchema` instead. */
  export const outboundSchema = GetCustomersData$outboundSchema;
  /** @deprecated use `GetCustomersData$Outbound` instead. */
  export type Outbound = GetCustomersData$Outbound;
}

export function getCustomersDataToJSON(
  getCustomersData: GetCustomersData,
): string {
  return JSON.stringify(
    GetCustomersData$outboundSchema.parse(getCustomersData),
  );
}

export function getCustomersDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersData' from JSON`,
  );
}

/** @internal */
export const GetCustomersPagination$inboundSchema: z.ZodType<
  GetCustomersPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/** @internal */
export type GetCustomersPagination$Outbound = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/** @internal */
export const GetCustomersPagination$outboundSchema: z.ZodType<
  GetCustomersPagination$Outbound,
  z.ZodTypeDef,
  GetCustomersPagination
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersPagination$ {
  /** @deprecated use `GetCustomersPagination$inboundSchema` instead. */
  export const inboundSchema = GetCustomersPagination$inboundSchema;
  /** @deprecated use `GetCustomersPagination$outboundSchema` instead. */
  export const outboundSchema = GetCustomersPagination$outboundSchema;
  /** @deprecated use `GetCustomersPagination$Outbound` instead. */
  export type Outbound = GetCustomersPagination$Outbound;
}

export function getCustomersPaginationToJSON(
  getCustomersPagination: GetCustomersPagination,
): string {
  return JSON.stringify(
    GetCustomersPagination$outboundSchema.parse(getCustomersPagination),
  );
}

export function getCustomersPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersPagination' from JSON`,
  );
}

/** @internal */
export const GetCustomersResponse$inboundSchema: z.ZodType<
  GetCustomersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => GetCustomersData$inboundSchema)),
  pagination: z.lazy(() => GetCustomersPagination$inboundSchema),
});

/** @internal */
export type GetCustomersResponse$Outbound = {
  data: Array<GetCustomersData$Outbound>;
  pagination: GetCustomersPagination$Outbound;
};

/** @internal */
export const GetCustomersResponse$outboundSchema: z.ZodType<
  GetCustomersResponse$Outbound,
  z.ZodTypeDef,
  GetCustomersResponse
> = z.object({
  data: z.array(z.lazy(() => GetCustomersData$outboundSchema)),
  pagination: z.lazy(() => GetCustomersPagination$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomersResponse$ {
  /** @deprecated use `GetCustomersResponse$inboundSchema` instead. */
  export const inboundSchema = GetCustomersResponse$inboundSchema;
  /** @deprecated use `GetCustomersResponse$outboundSchema` instead. */
  export const outboundSchema = GetCustomersResponse$outboundSchema;
  /** @deprecated use `GetCustomersResponse$Outbound` instead. */
  export type Outbound = GetCustomersResponse$Outbound;
}

export function getCustomersResponseToJSON(
  getCustomersResponse: GetCustomersResponse,
): string {
  return JSON.stringify(
    GetCustomersResponse$outboundSchema.parse(getCustomersResponse),
  );
}

export function getCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersResponse' from JSON`,
  );
}
