/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProductsIdRequest = {
  id: string;
};

export type GetProductsIdImages = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetProductsIdMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetProductsIdData = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/**
 * Get One Product
 */
export type GetProductsIdResponse = {
  success: boolean;
  data: GetProductsIdData;
};

/** @internal */
export const GetProductsIdRequest$inboundSchema: z.ZodType<
  GetProductsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetProductsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetProductsIdRequest$outboundSchema: z.ZodType<
  GetProductsIdRequest$Outbound,
  z.ZodTypeDef,
  GetProductsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsIdRequest$ {
  /** @deprecated use `GetProductsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetProductsIdRequest$inboundSchema;
  /** @deprecated use `GetProductsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetProductsIdRequest$outboundSchema;
  /** @deprecated use `GetProductsIdRequest$Outbound` instead. */
  export type Outbound = GetProductsIdRequest$Outbound;
}

export function getProductsIdRequestToJSON(
  getProductsIdRequest: GetProductsIdRequest,
): string {
  return JSON.stringify(
    GetProductsIdRequest$outboundSchema.parse(getProductsIdRequest),
  );
}

export function getProductsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsIdRequest' from JSON`,
  );
}

/** @internal */
export const GetProductsIdImages$inboundSchema: z.ZodType<
  GetProductsIdImages,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetProductsIdImages$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetProductsIdImages$outboundSchema: z.ZodType<
  GetProductsIdImages$Outbound,
  z.ZodTypeDef,
  GetProductsIdImages
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsIdImages$ {
  /** @deprecated use `GetProductsIdImages$inboundSchema` instead. */
  export const inboundSchema = GetProductsIdImages$inboundSchema;
  /** @deprecated use `GetProductsIdImages$outboundSchema` instead. */
  export const outboundSchema = GetProductsIdImages$outboundSchema;
  /** @deprecated use `GetProductsIdImages$Outbound` instead. */
  export type Outbound = GetProductsIdImages$Outbound;
}

export function getProductsIdImagesToJSON(
  getProductsIdImages: GetProductsIdImages,
): string {
  return JSON.stringify(
    GetProductsIdImages$outboundSchema.parse(getProductsIdImages),
  );
}

export function getProductsIdImagesFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsIdImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsIdImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsIdImages' from JSON`,
  );
}

/** @internal */
export const GetProductsIdMetadata$inboundSchema: z.ZodType<
  GetProductsIdMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetProductsIdMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetProductsIdMetadata$outboundSchema: z.ZodType<
  GetProductsIdMetadata$Outbound,
  z.ZodTypeDef,
  GetProductsIdMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsIdMetadata$ {
  /** @deprecated use `GetProductsIdMetadata$inboundSchema` instead. */
  export const inboundSchema = GetProductsIdMetadata$inboundSchema;
  /** @deprecated use `GetProductsIdMetadata$outboundSchema` instead. */
  export const outboundSchema = GetProductsIdMetadata$outboundSchema;
  /** @deprecated use `GetProductsIdMetadata$Outbound` instead. */
  export type Outbound = GetProductsIdMetadata$Outbound;
}

export function getProductsIdMetadataToJSON(
  getProductsIdMetadata: GetProductsIdMetadata,
): string {
  return JSON.stringify(
    GetProductsIdMetadata$outboundSchema.parse(getProductsIdMetadata),
  );
}

export function getProductsIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsIdMetadata' from JSON`,
  );
}

/** @internal */
export const GetProductsIdData$inboundSchema: z.ZodType<
  GetProductsIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/** @internal */
export type GetProductsIdData$Outbound = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/** @internal */
export const GetProductsIdData$outboundSchema: z.ZodType<
  GetProductsIdData$Outbound,
  z.ZodTypeDef,
  GetProductsIdData
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsIdData$ {
  /** @deprecated use `GetProductsIdData$inboundSchema` instead. */
  export const inboundSchema = GetProductsIdData$inboundSchema;
  /** @deprecated use `GetProductsIdData$outboundSchema` instead. */
  export const outboundSchema = GetProductsIdData$outboundSchema;
  /** @deprecated use `GetProductsIdData$Outbound` instead. */
  export type Outbound = GetProductsIdData$Outbound;
}

export function getProductsIdDataToJSON(
  getProductsIdData: GetProductsIdData,
): string {
  return JSON.stringify(
    GetProductsIdData$outboundSchema.parse(getProductsIdData),
  );
}

export function getProductsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsIdData' from JSON`,
  );
}

/** @internal */
export const GetProductsIdResponse$inboundSchema: z.ZodType<
  GetProductsIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetProductsIdData$inboundSchema),
});

/** @internal */
export type GetProductsIdResponse$Outbound = {
  success: boolean;
  data: GetProductsIdData$Outbound;
};

/** @internal */
export const GetProductsIdResponse$outboundSchema: z.ZodType<
  GetProductsIdResponse$Outbound,
  z.ZodTypeDef,
  GetProductsIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetProductsIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsIdResponse$ {
  /** @deprecated use `GetProductsIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetProductsIdResponse$inboundSchema;
  /** @deprecated use `GetProductsIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetProductsIdResponse$outboundSchema;
  /** @deprecated use `GetProductsIdResponse$Outbound` instead. */
  export type Outbound = GetProductsIdResponse$Outbound;
}

export function getProductsIdResponseToJSON(
  getProductsIdResponse: GetProductsIdResponse,
): string {
  return JSON.stringify(
    GetProductsIdResponse$outboundSchema.parse(getProductsIdResponse),
  );
}

export function getProductsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsIdResponse' from JSON`,
  );
}
