/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetProductsSortField = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Name: "name",
  Active: "active",
} as const;
export type GetProductsSortField = ClosedEnum<typeof GetProductsSortField>;

export const GetProductsSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetProductsSortOrder = ClosedEnum<typeof GetProductsSortOrder>;

export type GetProductsRequest = {
  query?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortField?: GetProductsSortField | undefined;
  sortOrder?: GetProductsSortOrder | undefined;
};

export type GetProductsImages =
  | string
  | number
  | boolean
  | { [k: string]: any }
  | Array<any>;

export type GetProductsMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetProductsData = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

export type GetProductsPagination = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/**
 * List of all products
 */
export type GetProductsResponse = {
  data: Array<GetProductsData>;
  pagination: GetProductsPagination;
};

/** @internal */
export const GetProductsSortField$inboundSchema: z.ZodNativeEnum<
  typeof GetProductsSortField
> = z.nativeEnum(GetProductsSortField);

/** @internal */
export const GetProductsSortField$outboundSchema: z.ZodNativeEnum<
  typeof GetProductsSortField
> = GetProductsSortField$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsSortField$ {
  /** @deprecated use `GetProductsSortField$inboundSchema` instead. */
  export const inboundSchema = GetProductsSortField$inboundSchema;
  /** @deprecated use `GetProductsSortField$outboundSchema` instead. */
  export const outboundSchema = GetProductsSortField$outboundSchema;
}

/** @internal */
export const GetProductsSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof GetProductsSortOrder
> = z.nativeEnum(GetProductsSortOrder);

/** @internal */
export const GetProductsSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetProductsSortOrder
> = GetProductsSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsSortOrder$ {
  /** @deprecated use `GetProductsSortOrder$inboundSchema` instead. */
  export const inboundSchema = GetProductsSortOrder$inboundSchema;
  /** @deprecated use `GetProductsSortOrder$outboundSchema` instead. */
  export const outboundSchema = GetProductsSortOrder$outboundSchema;
}

/** @internal */
export const GetProductsRequest$inboundSchema: z.ZodType<
  GetProductsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string().optional(),
  page: z.number().default(1),
  limit: z.number().default(10),
  sort_field: GetProductsSortField$inboundSchema.default("createdAt"),
  sort_order: GetProductsSortOrder$inboundSchema.default("desc"),
}).transform((v) => {
  return remap$(v, {
    "sort_field": "sortField",
    "sort_order": "sortOrder",
  });
});

/** @internal */
export type GetProductsRequest$Outbound = {
  query?: string | undefined;
  page: number;
  limit: number;
  sort_field: string;
  sort_order: string;
};

/** @internal */
export const GetProductsRequest$outboundSchema: z.ZodType<
  GetProductsRequest$Outbound,
  z.ZodTypeDef,
  GetProductsRequest
> = z.object({
  query: z.string().optional(),
  page: z.number().default(1),
  limit: z.number().default(10),
  sortField: GetProductsSortField$outboundSchema.default("createdAt"),
  sortOrder: GetProductsSortOrder$outboundSchema.default("desc"),
}).transform((v) => {
  return remap$(v, {
    sortField: "sort_field",
    sortOrder: "sort_order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsRequest$ {
  /** @deprecated use `GetProductsRequest$inboundSchema` instead. */
  export const inboundSchema = GetProductsRequest$inboundSchema;
  /** @deprecated use `GetProductsRequest$outboundSchema` instead. */
  export const outboundSchema = GetProductsRequest$outboundSchema;
  /** @deprecated use `GetProductsRequest$Outbound` instead. */
  export type Outbound = GetProductsRequest$Outbound;
}

export function getProductsRequestToJSON(
  getProductsRequest: GetProductsRequest,
): string {
  return JSON.stringify(
    GetProductsRequest$outboundSchema.parse(getProductsRequest),
  );
}

export function getProductsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsRequest' from JSON`,
  );
}

/** @internal */
export const GetProductsImages$inboundSchema: z.ZodType<
  GetProductsImages,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetProductsImages$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetProductsImages$outboundSchema: z.ZodType<
  GetProductsImages$Outbound,
  z.ZodTypeDef,
  GetProductsImages
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsImages$ {
  /** @deprecated use `GetProductsImages$inboundSchema` instead. */
  export const inboundSchema = GetProductsImages$inboundSchema;
  /** @deprecated use `GetProductsImages$outboundSchema` instead. */
  export const outboundSchema = GetProductsImages$outboundSchema;
  /** @deprecated use `GetProductsImages$Outbound` instead. */
  export type Outbound = GetProductsImages$Outbound;
}

export function getProductsImagesToJSON(
  getProductsImages: GetProductsImages,
): string {
  return JSON.stringify(
    GetProductsImages$outboundSchema.parse(getProductsImages),
  );
}

export function getProductsImagesFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsImages' from JSON`,
  );
}

/** @internal */
export const GetProductsMetadata$inboundSchema: z.ZodType<
  GetProductsMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetProductsMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetProductsMetadata$outboundSchema: z.ZodType<
  GetProductsMetadata$Outbound,
  z.ZodTypeDef,
  GetProductsMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsMetadata$ {
  /** @deprecated use `GetProductsMetadata$inboundSchema` instead. */
  export const inboundSchema = GetProductsMetadata$inboundSchema;
  /** @deprecated use `GetProductsMetadata$outboundSchema` instead. */
  export const outboundSchema = GetProductsMetadata$outboundSchema;
  /** @deprecated use `GetProductsMetadata$Outbound` instead. */
  export type Outbound = GetProductsMetadata$Outbound;
}

export function getProductsMetadataToJSON(
  getProductsMetadata: GetProductsMetadata,
): string {
  return JSON.stringify(
    GetProductsMetadata$outboundSchema.parse(getProductsMetadata),
  );
}

export function getProductsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsMetadata' from JSON`,
  );
}

/** @internal */
export const GetProductsData$inboundSchema: z.ZodType<
  GetProductsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/** @internal */
export type GetProductsData$Outbound = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/** @internal */
export const GetProductsData$outboundSchema: z.ZodType<
  GetProductsData$Outbound,
  z.ZodTypeDef,
  GetProductsData
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsData$ {
  /** @deprecated use `GetProductsData$inboundSchema` instead. */
  export const inboundSchema = GetProductsData$inboundSchema;
  /** @deprecated use `GetProductsData$outboundSchema` instead. */
  export const outboundSchema = GetProductsData$outboundSchema;
  /** @deprecated use `GetProductsData$Outbound` instead. */
  export type Outbound = GetProductsData$Outbound;
}

export function getProductsDataToJSON(
  getProductsData: GetProductsData,
): string {
  return JSON.stringify(GetProductsData$outboundSchema.parse(getProductsData));
}

export function getProductsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsData' from JSON`,
  );
}

/** @internal */
export const GetProductsPagination$inboundSchema: z.ZodType<
  GetProductsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/** @internal */
export type GetProductsPagination$Outbound = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/** @internal */
export const GetProductsPagination$outboundSchema: z.ZodType<
  GetProductsPagination$Outbound,
  z.ZodTypeDef,
  GetProductsPagination
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsPagination$ {
  /** @deprecated use `GetProductsPagination$inboundSchema` instead. */
  export const inboundSchema = GetProductsPagination$inboundSchema;
  /** @deprecated use `GetProductsPagination$outboundSchema` instead. */
  export const outboundSchema = GetProductsPagination$outboundSchema;
  /** @deprecated use `GetProductsPagination$Outbound` instead. */
  export type Outbound = GetProductsPagination$Outbound;
}

export function getProductsPaginationToJSON(
  getProductsPagination: GetProductsPagination,
): string {
  return JSON.stringify(
    GetProductsPagination$outboundSchema.parse(getProductsPagination),
  );
}

export function getProductsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsPagination' from JSON`,
  );
}

/** @internal */
export const GetProductsResponse$inboundSchema: z.ZodType<
  GetProductsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => GetProductsData$inboundSchema)),
  pagination: z.lazy(() => GetProductsPagination$inboundSchema),
});

/** @internal */
export type GetProductsResponse$Outbound = {
  data: Array<GetProductsData$Outbound>;
  pagination: GetProductsPagination$Outbound;
};

/** @internal */
export const GetProductsResponse$outboundSchema: z.ZodType<
  GetProductsResponse$Outbound,
  z.ZodTypeDef,
  GetProductsResponse
> = z.object({
  data: z.array(z.lazy(() => GetProductsData$outboundSchema)),
  pagination: z.lazy(() => GetProductsPagination$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsResponse$ {
  /** @deprecated use `GetProductsResponse$inboundSchema` instead. */
  export const inboundSchema = GetProductsResponse$inboundSchema;
  /** @deprecated use `GetProductsResponse$outboundSchema` instead. */
  export const outboundSchema = GetProductsResponse$outboundSchema;
  /** @deprecated use `GetProductsResponse$Outbound` instead. */
  export type Outbound = GetProductsResponse$Outbound;
}

export function getProductsResponseToJSON(
  getProductsResponse: GetProductsResponse,
): string {
  return JSON.stringify(
    GetProductsResponse$outboundSchema.parse(getProductsResponse),
  );
}

export function getProductsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProductsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductsResponse' from JSON`,
  );
}
