/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTransactionsIdRequest = {
  id: string;
};

export const GetTransactionsIdStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type GetTransactionsIdStatus = ClosedEnum<
  typeof GetTransactionsIdStatus
>;

export const GetTransactionsIdType = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type GetTransactionsIdType = ClosedEnum<typeof GetTransactionsIdType>;

export type GetTransactionsIdMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export const GetTransactionsIdOrigin = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type GetTransactionsIdOrigin = ClosedEnum<
  typeof GetTransactionsIdOrigin
>;

export type GetTransactionsIdData = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: GetTransactionsIdStatus;
  type: GetTransactionsIdType;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: GetTransactionsIdOrigin | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

/**
 * Get One Transaction
 */
export type GetTransactionsIdResponse = {
  success: boolean;
  data: GetTransactionsIdData;
};

/** @internal */
export const GetTransactionsIdRequest$inboundSchema: z.ZodType<
  GetTransactionsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetTransactionsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTransactionsIdRequest$outboundSchema: z.ZodType<
  GetTransactionsIdRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdRequest$ {
  /** @deprecated use `GetTransactionsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdRequest$inboundSchema;
  /** @deprecated use `GetTransactionsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdRequest$outboundSchema;
  /** @deprecated use `GetTransactionsIdRequest$Outbound` instead. */
  export type Outbound = GetTransactionsIdRequest$Outbound;
}

export function getTransactionsIdRequestToJSON(
  getTransactionsIdRequest: GetTransactionsIdRequest,
): string {
  return JSON.stringify(
    GetTransactionsIdRequest$outboundSchema.parse(getTransactionsIdRequest),
  );
}

export function getTransactionsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsIdRequest' from JSON`,
  );
}

/** @internal */
export const GetTransactionsIdStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdStatus
> = z.nativeEnum(GetTransactionsIdStatus);

/** @internal */
export const GetTransactionsIdStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdStatus
> = GetTransactionsIdStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdStatus$ {
  /** @deprecated use `GetTransactionsIdStatus$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdStatus$inboundSchema;
  /** @deprecated use `GetTransactionsIdStatus$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdStatus$outboundSchema;
}

/** @internal */
export const GetTransactionsIdType$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdType
> = z.nativeEnum(GetTransactionsIdType);

/** @internal */
export const GetTransactionsIdType$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdType
> = GetTransactionsIdType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdType$ {
  /** @deprecated use `GetTransactionsIdType$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdType$inboundSchema;
  /** @deprecated use `GetTransactionsIdType$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdType$outboundSchema;
}

/** @internal */
export const GetTransactionsIdMetadata$inboundSchema: z.ZodType<
  GetTransactionsIdMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetTransactionsIdMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetTransactionsIdMetadata$outboundSchema: z.ZodType<
  GetTransactionsIdMetadata$Outbound,
  z.ZodTypeDef,
  GetTransactionsIdMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdMetadata$ {
  /** @deprecated use `GetTransactionsIdMetadata$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdMetadata$inboundSchema;
  /** @deprecated use `GetTransactionsIdMetadata$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdMetadata$outboundSchema;
  /** @deprecated use `GetTransactionsIdMetadata$Outbound` instead. */
  export type Outbound = GetTransactionsIdMetadata$Outbound;
}

export function getTransactionsIdMetadataToJSON(
  getTransactionsIdMetadata: GetTransactionsIdMetadata,
): string {
  return JSON.stringify(
    GetTransactionsIdMetadata$outboundSchema.parse(getTransactionsIdMetadata),
  );
}

export function getTransactionsIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsIdMetadata' from JSON`,
  );
}

/** @internal */
export const GetTransactionsIdOrigin$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdOrigin
> = z.nativeEnum(GetTransactionsIdOrigin);

/** @internal */
export const GetTransactionsIdOrigin$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsIdOrigin
> = GetTransactionsIdOrigin$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdOrigin$ {
  /** @deprecated use `GetTransactionsIdOrigin$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdOrigin$inboundSchema;
  /** @deprecated use `GetTransactionsIdOrigin$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdOrigin$outboundSchema;
}

/** @internal */
export const GetTransactionsIdData$inboundSchema: z.ZodType<
  GetTransactionsIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: GetTransactionsIdStatus$inboundSchema,
  type: GetTransactionsIdType$inboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(GetTransactionsIdOrigin$inboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/** @internal */
export type GetTransactionsIdData$Outbound = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: string;
  type: string;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: string | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

/** @internal */
export const GetTransactionsIdData$outboundSchema: z.ZodType<
  GetTransactionsIdData$Outbound,
  z.ZodTypeDef,
  GetTransactionsIdData
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: GetTransactionsIdStatus$outboundSchema,
  type: GetTransactionsIdType$outboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(GetTransactionsIdOrigin$outboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdData$ {
  /** @deprecated use `GetTransactionsIdData$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdData$inboundSchema;
  /** @deprecated use `GetTransactionsIdData$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdData$outboundSchema;
  /** @deprecated use `GetTransactionsIdData$Outbound` instead. */
  export type Outbound = GetTransactionsIdData$Outbound;
}

export function getTransactionsIdDataToJSON(
  getTransactionsIdData: GetTransactionsIdData,
): string {
  return JSON.stringify(
    GetTransactionsIdData$outboundSchema.parse(getTransactionsIdData),
  );
}

export function getTransactionsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsIdData' from JSON`,
  );
}

/** @internal */
export const GetTransactionsIdResponse$inboundSchema: z.ZodType<
  GetTransactionsIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetTransactionsIdData$inboundSchema),
});

/** @internal */
export type GetTransactionsIdResponse$Outbound = {
  success: boolean;
  data: GetTransactionsIdData$Outbound;
};

/** @internal */
export const GetTransactionsIdResponse$outboundSchema: z.ZodType<
  GetTransactionsIdResponse$Outbound,
  z.ZodTypeDef,
  GetTransactionsIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => GetTransactionsIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsIdResponse$ {
  /** @deprecated use `GetTransactionsIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsIdResponse$inboundSchema;
  /** @deprecated use `GetTransactionsIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsIdResponse$outboundSchema;
  /** @deprecated use `GetTransactionsIdResponse$Outbound` instead. */
  export type Outbound = GetTransactionsIdResponse$Outbound;
}

export function getTransactionsIdResponseToJSON(
  getTransactionsIdResponse: GetTransactionsIdResponse,
): string {
  return JSON.stringify(
    GetTransactionsIdResponse$outboundSchema.parse(getTransactionsIdResponse),
  );
}

export function getTransactionsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsIdResponse' from JSON`,
  );
}
