/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTransactionsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
};

export const GetTransactionsStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type GetTransactionsStatus = ClosedEnum<typeof GetTransactionsStatus>;

export const GetTransactionsType = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type GetTransactionsType = ClosedEnum<typeof GetTransactionsType>;

export type GetTransactionsMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export const GetTransactionsOrigin = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type GetTransactionsOrigin = ClosedEnum<typeof GetTransactionsOrigin>;

export type GetTransactionsData = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: GetTransactionsStatus;
  type: GetTransactionsType;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: GetTransactionsOrigin | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

export type GetTransactionsPagination = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/**
 * List of all transactions
 */
export type GetTransactionsResponse = {
  data: Array<GetTransactionsData>;
  pagination: GetTransactionsPagination;
};

/** @internal */
export const GetTransactionsRequest$inboundSchema: z.ZodType<
  GetTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().default(1),
  limit: z.number().default(10),
});

/** @internal */
export type GetTransactionsRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const GetTransactionsRequest$outboundSchema: z.ZodType<
  GetTransactionsRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsRequest
> = z.object({
  page: z.number().default(1),
  limit: z.number().default(10),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsRequest$ {
  /** @deprecated use `GetTransactionsRequest$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsRequest$inboundSchema;
  /** @deprecated use `GetTransactionsRequest$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsRequest$outboundSchema;
  /** @deprecated use `GetTransactionsRequest$Outbound` instead. */
  export type Outbound = GetTransactionsRequest$Outbound;
}

export function getTransactionsRequestToJSON(
  getTransactionsRequest: GetTransactionsRequest,
): string {
  return JSON.stringify(
    GetTransactionsRequest$outboundSchema.parse(getTransactionsRequest),
  );
}

export function getTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsRequest' from JSON`,
  );
}

/** @internal */
export const GetTransactionsStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsStatus
> = z.nativeEnum(GetTransactionsStatus);

/** @internal */
export const GetTransactionsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsStatus
> = GetTransactionsStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsStatus$ {
  /** @deprecated use `GetTransactionsStatus$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsStatus$inboundSchema;
  /** @deprecated use `GetTransactionsStatus$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsStatus$outboundSchema;
}

/** @internal */
export const GetTransactionsType$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsType
> = z.nativeEnum(GetTransactionsType);

/** @internal */
export const GetTransactionsType$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsType
> = GetTransactionsType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsType$ {
  /** @deprecated use `GetTransactionsType$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsType$inboundSchema;
  /** @deprecated use `GetTransactionsType$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsType$outboundSchema;
}

/** @internal */
export const GetTransactionsMetadata$inboundSchema: z.ZodType<
  GetTransactionsMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type GetTransactionsMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const GetTransactionsMetadata$outboundSchema: z.ZodType<
  GetTransactionsMetadata$Outbound,
  z.ZodTypeDef,
  GetTransactionsMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsMetadata$ {
  /** @deprecated use `GetTransactionsMetadata$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsMetadata$inboundSchema;
  /** @deprecated use `GetTransactionsMetadata$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsMetadata$outboundSchema;
  /** @deprecated use `GetTransactionsMetadata$Outbound` instead. */
  export type Outbound = GetTransactionsMetadata$Outbound;
}

export function getTransactionsMetadataToJSON(
  getTransactionsMetadata: GetTransactionsMetadata,
): string {
  return JSON.stringify(
    GetTransactionsMetadata$outboundSchema.parse(getTransactionsMetadata),
  );
}

export function getTransactionsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsMetadata' from JSON`,
  );
}

/** @internal */
export const GetTransactionsOrigin$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsOrigin
> = z.nativeEnum(GetTransactionsOrigin);

/** @internal */
export const GetTransactionsOrigin$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsOrigin
> = GetTransactionsOrigin$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsOrigin$ {
  /** @deprecated use `GetTransactionsOrigin$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsOrigin$inboundSchema;
  /** @deprecated use `GetTransactionsOrigin$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsOrigin$outboundSchema;
}

/** @internal */
export const GetTransactionsData$inboundSchema: z.ZodType<
  GetTransactionsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: GetTransactionsStatus$inboundSchema,
  type: GetTransactionsType$inboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(GetTransactionsOrigin$inboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/** @internal */
export type GetTransactionsData$Outbound = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: string;
  type: string;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: string | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

/** @internal */
export const GetTransactionsData$outboundSchema: z.ZodType<
  GetTransactionsData$Outbound,
  z.ZodTypeDef,
  GetTransactionsData
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: GetTransactionsStatus$outboundSchema,
  type: GetTransactionsType$outboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(GetTransactionsOrigin$outboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsData$ {
  /** @deprecated use `GetTransactionsData$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsData$inboundSchema;
  /** @deprecated use `GetTransactionsData$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsData$outboundSchema;
  /** @deprecated use `GetTransactionsData$Outbound` instead. */
  export type Outbound = GetTransactionsData$Outbound;
}

export function getTransactionsDataToJSON(
  getTransactionsData: GetTransactionsData,
): string {
  return JSON.stringify(
    GetTransactionsData$outboundSchema.parse(getTransactionsData),
  );
}

export function getTransactionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsData' from JSON`,
  );
}

/** @internal */
export const GetTransactionsPagination$inboundSchema: z.ZodType<
  GetTransactionsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/** @internal */
export type GetTransactionsPagination$Outbound = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
};

/** @internal */
export const GetTransactionsPagination$outboundSchema: z.ZodType<
  GetTransactionsPagination$Outbound,
  z.ZodTypeDef,
  GetTransactionsPagination
> = z.object({
  totalCount: z.number(),
  maxPage: z.number(),
  currentPage: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsPagination$ {
  /** @deprecated use `GetTransactionsPagination$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsPagination$inboundSchema;
  /** @deprecated use `GetTransactionsPagination$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsPagination$outboundSchema;
  /** @deprecated use `GetTransactionsPagination$Outbound` instead. */
  export type Outbound = GetTransactionsPagination$Outbound;
}

export function getTransactionsPaginationToJSON(
  getTransactionsPagination: GetTransactionsPagination,
): string {
  return JSON.stringify(
    GetTransactionsPagination$outboundSchema.parse(getTransactionsPagination),
  );
}

export function getTransactionsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsPagination' from JSON`,
  );
}

/** @internal */
export const GetTransactionsResponse$inboundSchema: z.ZodType<
  GetTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => GetTransactionsData$inboundSchema)),
  pagination: z.lazy(() => GetTransactionsPagination$inboundSchema),
});

/** @internal */
export type GetTransactionsResponse$Outbound = {
  data: Array<GetTransactionsData$Outbound>;
  pagination: GetTransactionsPagination$Outbound;
};

/** @internal */
export const GetTransactionsResponse$outboundSchema: z.ZodType<
  GetTransactionsResponse$Outbound,
  z.ZodTypeDef,
  GetTransactionsResponse
> = z.object({
  data: z.array(z.lazy(() => GetTransactionsData$outboundSchema)),
  pagination: z.lazy(() => GetTransactionsPagination$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsResponse$ {
  /** @deprecated use `GetTransactionsResponse$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsResponse$inboundSchema;
  /** @deprecated use `GetTransactionsResponse$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsResponse$outboundSchema;
  /** @deprecated use `GetTransactionsResponse$Outbound` instead. */
  export type Outbound = GetTransactionsResponse$Outbound;
}

export function getTransactionsResponseToJSON(
  getTransactionsResponse: GetTransactionsResponse,
): string {
  return JSON.stringify(
    GetTransactionsResponse$outboundSchema.parse(getTransactionsResponse),
  );
}

export function getTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsResponse' from JSON`,
  );
}
