/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The customer id
 */
export type PatchCustomersIdRequestBody = {
  name?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  balance?: string | undefined;
  description?: string | undefined;
};

export type PatchCustomersIdRequest = {
  id: string;
  /**
   * The customer id
   */
  requestBody: PatchCustomersIdRequestBody;
};

export type PatchCustomersIdMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PatchCustomersIdData = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

/**
 * Updated Customer
 */
export type PatchCustomersIdResponse = {
  success: boolean;
  data: PatchCustomersIdData;
};

/** @internal */
export const PatchCustomersIdRequestBody$inboundSchema: z.ZodType<
  PatchCustomersIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  email: z.string().optional(),
  phoneNumber: z.string().optional(),
  balance: z.string().optional(),
  description: z.string().optional(),
});

/** @internal */
export type PatchCustomersIdRequestBody$Outbound = {
  name?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  balance?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const PatchCustomersIdRequestBody$outboundSchema: z.ZodType<
  PatchCustomersIdRequestBody$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdRequestBody
> = z.object({
  name: z.string().optional(),
  email: z.string().optional(),
  phoneNumber: z.string().optional(),
  balance: z.string().optional(),
  description: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdRequestBody$ {
  /** @deprecated use `PatchCustomersIdRequestBody$inboundSchema` instead. */
  export const inboundSchema = PatchCustomersIdRequestBody$inboundSchema;
  /** @deprecated use `PatchCustomersIdRequestBody$outboundSchema` instead. */
  export const outboundSchema = PatchCustomersIdRequestBody$outboundSchema;
  /** @deprecated use `PatchCustomersIdRequestBody$Outbound` instead. */
  export type Outbound = PatchCustomersIdRequestBody$Outbound;
}

export function patchCustomersIdRequestBodyToJSON(
  patchCustomersIdRequestBody: PatchCustomersIdRequestBody,
): string {
  return JSON.stringify(
    PatchCustomersIdRequestBody$outboundSchema.parse(
      patchCustomersIdRequestBody,
    ),
  );
}

export function patchCustomersIdRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersIdRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdRequestBody' from JSON`,
  );
}

/** @internal */
export const PatchCustomersIdRequest$inboundSchema: z.ZodType<
  PatchCustomersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => PatchCustomersIdRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchCustomersIdRequest$Outbound = {
  id: string;
  RequestBody: PatchCustomersIdRequestBody$Outbound;
};

/** @internal */
export const PatchCustomersIdRequest$outboundSchema: z.ZodType<
  PatchCustomersIdRequest$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => PatchCustomersIdRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdRequest$ {
  /** @deprecated use `PatchCustomersIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchCustomersIdRequest$inboundSchema;
  /** @deprecated use `PatchCustomersIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchCustomersIdRequest$outboundSchema;
  /** @deprecated use `PatchCustomersIdRequest$Outbound` instead. */
  export type Outbound = PatchCustomersIdRequest$Outbound;
}

export function patchCustomersIdRequestToJSON(
  patchCustomersIdRequest: PatchCustomersIdRequest,
): string {
  return JSON.stringify(
    PatchCustomersIdRequest$outboundSchema.parse(patchCustomersIdRequest),
  );
}

export function patchCustomersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdRequest' from JSON`,
  );
}

/** @internal */
export const PatchCustomersIdMetadata$inboundSchema: z.ZodType<
  PatchCustomersIdMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PatchCustomersIdMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PatchCustomersIdMetadata$outboundSchema: z.ZodType<
  PatchCustomersIdMetadata$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdMetadata$ {
  /** @deprecated use `PatchCustomersIdMetadata$inboundSchema` instead. */
  export const inboundSchema = PatchCustomersIdMetadata$inboundSchema;
  /** @deprecated use `PatchCustomersIdMetadata$outboundSchema` instead. */
  export const outboundSchema = PatchCustomersIdMetadata$outboundSchema;
  /** @deprecated use `PatchCustomersIdMetadata$Outbound` instead. */
  export type Outbound = PatchCustomersIdMetadata$Outbound;
}

export function patchCustomersIdMetadataToJSON(
  patchCustomersIdMetadata: PatchCustomersIdMetadata,
): string {
  return JSON.stringify(
    PatchCustomersIdMetadata$outboundSchema.parse(patchCustomersIdMetadata),
  );
}

export function patchCustomersIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdMetadata' from JSON`,
  );
}

/** @internal */
export const PatchCustomersIdData$inboundSchema: z.ZodType<
  PatchCustomersIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/** @internal */
export type PatchCustomersIdData$Outbound = {
  id: string;
  name: string | null;
  description: string | null;
  balance: string;
  livemode: boolean;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  currency: string;
  email: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastActiveAt: string | null;
};

/** @internal */
export const PatchCustomersIdData$outboundSchema: z.ZodType<
  PatchCustomersIdData$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdData
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  description: z.nullable(z.string()),
  balance: z.string(),
  livemode: z.boolean(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  currency: z.string(),
  email: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
  lastActiveAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdData$ {
  /** @deprecated use `PatchCustomersIdData$inboundSchema` instead. */
  export const inboundSchema = PatchCustomersIdData$inboundSchema;
  /** @deprecated use `PatchCustomersIdData$outboundSchema` instead. */
  export const outboundSchema = PatchCustomersIdData$outboundSchema;
  /** @deprecated use `PatchCustomersIdData$Outbound` instead. */
  export type Outbound = PatchCustomersIdData$Outbound;
}

export function patchCustomersIdDataToJSON(
  patchCustomersIdData: PatchCustomersIdData,
): string {
  return JSON.stringify(
    PatchCustomersIdData$outboundSchema.parse(patchCustomersIdData),
  );
}

export function patchCustomersIdDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdData' from JSON`,
  );
}

/** @internal */
export const PatchCustomersIdResponse$inboundSchema: z.ZodType<
  PatchCustomersIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchCustomersIdData$inboundSchema),
});

/** @internal */
export type PatchCustomersIdResponse$Outbound = {
  success: boolean;
  data: PatchCustomersIdData$Outbound;
};

/** @internal */
export const PatchCustomersIdResponse$outboundSchema: z.ZodType<
  PatchCustomersIdResponse$Outbound,
  z.ZodTypeDef,
  PatchCustomersIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchCustomersIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersIdResponse$ {
  /** @deprecated use `PatchCustomersIdResponse$inboundSchema` instead. */
  export const inboundSchema = PatchCustomersIdResponse$inboundSchema;
  /** @deprecated use `PatchCustomersIdResponse$outboundSchema` instead. */
  export const outboundSchema = PatchCustomersIdResponse$outboundSchema;
  /** @deprecated use `PatchCustomersIdResponse$Outbound` instead. */
  export type Outbound = PatchCustomersIdResponse$Outbound;
}

export function patchCustomersIdResponseToJSON(
  patchCustomersIdResponse: PatchCustomersIdResponse,
): string {
  return JSON.stringify(
    PatchCustomersIdResponse$outboundSchema.parse(patchCustomersIdResponse),
  );
}

export function patchCustomersIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersIdResponse' from JSON`,
  );
}
