/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PatchTransactionsIdStatusRequest = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type PatchTransactionsIdStatusRequest = ClosedEnum<
  typeof PatchTransactionsIdStatusRequest
>;

export const PatchTransactionsIdTypeRequest = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type PatchTransactionsIdTypeRequest = ClosedEnum<
  typeof PatchTransactionsIdTypeRequest
>;

export const PatchTransactionsIdOriginRequest = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type PatchTransactionsIdOriginRequest = ClosedEnum<
  typeof PatchTransactionsIdOriginRequest
>;

export const PatchTransactionsIdProvider = {
  Mpesa: "mpesa",
} as const;
export type PatchTransactionsIdProvider = ClosedEnum<
  typeof PatchTransactionsIdProvider
>;

export type PatchTransactionsIdInitialRequest = {
  merchantRequestId: string | null;
  checkoutRequestId: string | null;
  responseCode: string | null;
  responseDescription: string | null;
  customerMessage: string | null;
};

export type PatchTransactionsIdCallbackResult = {
  resultCode: number | null;
  resultDescription: string | null;
  receiptNumber: string | null;
  amount: number | null;
  transactionDate: string | null;
  phoneNumber: string | null;
};

export type PatchTransactionsIdMetadataRequest = {
  provider: PatchTransactionsIdProvider;
  initialRequest: PatchTransactionsIdInitialRequest;
  callbackResult: PatchTransactionsIdCallbackResult;
};

/**
 * The transaction update data
 */
export type PatchTransactionsIdRequestBody = {
  customerId?: string | undefined;
  amount?: string | undefined;
  currency?: string | undefined;
  provider?: string | undefined;
  providerReference?: string | undefined;
  description?: string | undefined;
  status?: PatchTransactionsIdStatusRequest | undefined;
  type?: PatchTransactionsIdTypeRequest | undefined;
  origin?: PatchTransactionsIdOriginRequest | undefined;
  metadata?: PatchTransactionsIdMetadataRequest | null | undefined;
};

export type PatchTransactionsIdRequest = {
  id: string;
  /**
   * The transaction update data
   */
  requestBody: PatchTransactionsIdRequestBody;
};

export const PatchTransactionsIdStatusResponse = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type PatchTransactionsIdStatusResponse = ClosedEnum<
  typeof PatchTransactionsIdStatusResponse
>;

export const PatchTransactionsIdTypeResponse = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type PatchTransactionsIdTypeResponse = ClosedEnum<
  typeof PatchTransactionsIdTypeResponse
>;

export type PatchTransactionsIdMetadataResponse = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export const PatchTransactionsIdOriginResponse = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type PatchTransactionsIdOriginResponse = ClosedEnum<
  typeof PatchTransactionsIdOriginResponse
>;

export type PatchTransactionsIdData = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: PatchTransactionsIdStatusResponse;
  type: PatchTransactionsIdTypeResponse;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: PatchTransactionsIdOriginResponse | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

/**
 * Updated Transaction
 */
export type PatchTransactionsIdResponse = {
  success: boolean;
  data: PatchTransactionsIdData;
};

/** @internal */
export const PatchTransactionsIdStatusRequest$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdStatusRequest
> = z.nativeEnum(PatchTransactionsIdStatusRequest);

/** @internal */
export const PatchTransactionsIdStatusRequest$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdStatusRequest
> = PatchTransactionsIdStatusRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdStatusRequest$ {
  /** @deprecated use `PatchTransactionsIdStatusRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdStatusRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdStatusRequest$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdStatusRequest$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdTypeRequest$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdTypeRequest
> = z.nativeEnum(PatchTransactionsIdTypeRequest);

/** @internal */
export const PatchTransactionsIdTypeRequest$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdTypeRequest
> = PatchTransactionsIdTypeRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdTypeRequest$ {
  /** @deprecated use `PatchTransactionsIdTypeRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdTypeRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdTypeRequest$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdTypeRequest$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdOriginRequest$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdOriginRequest
> = z.nativeEnum(PatchTransactionsIdOriginRequest);

/** @internal */
export const PatchTransactionsIdOriginRequest$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdOriginRequest
> = PatchTransactionsIdOriginRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdOriginRequest$ {
  /** @deprecated use `PatchTransactionsIdOriginRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdOriginRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdOriginRequest$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdOriginRequest$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdProvider$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdProvider
> = z.nativeEnum(PatchTransactionsIdProvider);

/** @internal */
export const PatchTransactionsIdProvider$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdProvider
> = PatchTransactionsIdProvider$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdProvider$ {
  /** @deprecated use `PatchTransactionsIdProvider$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdProvider$inboundSchema;
  /** @deprecated use `PatchTransactionsIdProvider$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdProvider$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdInitialRequest$inboundSchema: z.ZodType<
  PatchTransactionsIdInitialRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  responseCode: z.nullable(z.string()),
  responseDescription: z.nullable(z.string()),
  customerMessage: z.nullable(z.string()),
});

/** @internal */
export type PatchTransactionsIdInitialRequest$Outbound = {
  merchantRequestId: string | null;
  checkoutRequestId: string | null;
  responseCode: string | null;
  responseDescription: string | null;
  customerMessage: string | null;
};

/** @internal */
export const PatchTransactionsIdInitialRequest$outboundSchema: z.ZodType<
  PatchTransactionsIdInitialRequest$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdInitialRequest
> = z.object({
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  responseCode: z.nullable(z.string()),
  responseDescription: z.nullable(z.string()),
  customerMessage: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdInitialRequest$ {
  /** @deprecated use `PatchTransactionsIdInitialRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdInitialRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdInitialRequest$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdInitialRequest$outboundSchema;
  /** @deprecated use `PatchTransactionsIdInitialRequest$Outbound` instead. */
  export type Outbound = PatchTransactionsIdInitialRequest$Outbound;
}

export function patchTransactionsIdInitialRequestToJSON(
  patchTransactionsIdInitialRequest: PatchTransactionsIdInitialRequest,
): string {
  return JSON.stringify(
    PatchTransactionsIdInitialRequest$outboundSchema.parse(
      patchTransactionsIdInitialRequest,
    ),
  );
}

export function patchTransactionsIdInitialRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdInitialRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdInitialRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdInitialRequest' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdCallbackResult$inboundSchema: z.ZodType<
  PatchTransactionsIdCallbackResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.nullable(z.number()),
  resultDescription: z.nullable(z.string()),
  receiptNumber: z.nullable(z.string()),
  amount: z.nullable(z.number()),
  transactionDate: z.nullable(z.string()),
  phoneNumber: z.nullable(z.string()),
});

/** @internal */
export type PatchTransactionsIdCallbackResult$Outbound = {
  resultCode: number | null;
  resultDescription: string | null;
  receiptNumber: string | null;
  amount: number | null;
  transactionDate: string | null;
  phoneNumber: string | null;
};

/** @internal */
export const PatchTransactionsIdCallbackResult$outboundSchema: z.ZodType<
  PatchTransactionsIdCallbackResult$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdCallbackResult
> = z.object({
  resultCode: z.nullable(z.number()),
  resultDescription: z.nullable(z.string()),
  receiptNumber: z.nullable(z.string()),
  amount: z.nullable(z.number()),
  transactionDate: z.nullable(z.string()),
  phoneNumber: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdCallbackResult$ {
  /** @deprecated use `PatchTransactionsIdCallbackResult$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdCallbackResult$inboundSchema;
  /** @deprecated use `PatchTransactionsIdCallbackResult$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdCallbackResult$outboundSchema;
  /** @deprecated use `PatchTransactionsIdCallbackResult$Outbound` instead. */
  export type Outbound = PatchTransactionsIdCallbackResult$Outbound;
}

export function patchTransactionsIdCallbackResultToJSON(
  patchTransactionsIdCallbackResult: PatchTransactionsIdCallbackResult,
): string {
  return JSON.stringify(
    PatchTransactionsIdCallbackResult$outboundSchema.parse(
      patchTransactionsIdCallbackResult,
    ),
  );
}

export function patchTransactionsIdCallbackResultFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdCallbackResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdCallbackResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdCallbackResult' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdMetadataRequest$inboundSchema: z.ZodType<
  PatchTransactionsIdMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  provider: PatchTransactionsIdProvider$inboundSchema,
  initialRequest: z.lazy(() => PatchTransactionsIdInitialRequest$inboundSchema),
  callbackResult: z.lazy(() => PatchTransactionsIdCallbackResult$inboundSchema),
});

/** @internal */
export type PatchTransactionsIdMetadataRequest$Outbound = {
  provider: string;
  initialRequest: PatchTransactionsIdInitialRequest$Outbound;
  callbackResult: PatchTransactionsIdCallbackResult$Outbound;
};

/** @internal */
export const PatchTransactionsIdMetadataRequest$outboundSchema: z.ZodType<
  PatchTransactionsIdMetadataRequest$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdMetadataRequest
> = z.object({
  provider: PatchTransactionsIdProvider$outboundSchema,
  initialRequest: z.lazy(() =>
    PatchTransactionsIdInitialRequest$outboundSchema
  ),
  callbackResult: z.lazy(() =>
    PatchTransactionsIdCallbackResult$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdMetadataRequest$ {
  /** @deprecated use `PatchTransactionsIdMetadataRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdMetadataRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdMetadataRequest$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdMetadataRequest$outboundSchema;
  /** @deprecated use `PatchTransactionsIdMetadataRequest$Outbound` instead. */
  export type Outbound = PatchTransactionsIdMetadataRequest$Outbound;
}

export function patchTransactionsIdMetadataRequestToJSON(
  patchTransactionsIdMetadataRequest: PatchTransactionsIdMetadataRequest,
): string {
  return JSON.stringify(
    PatchTransactionsIdMetadataRequest$outboundSchema.parse(
      patchTransactionsIdMetadataRequest,
    ),
  );
}

export function patchTransactionsIdMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchTransactionsIdMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdMetadataRequest' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdRequestBody$inboundSchema: z.ZodType<
  PatchTransactionsIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string().optional(),
  amount: z.string().optional(),
  currency: z.string().optional(),
  provider: z.string().optional(),
  providerReference: z.string().optional(),
  description: z.string().optional(),
  status: PatchTransactionsIdStatusRequest$inboundSchema.optional(),
  type: PatchTransactionsIdTypeRequest$inboundSchema.optional(),
  origin: PatchTransactionsIdOriginRequest$inboundSchema.optional(),
  metadata: z.nullable(
    z.lazy(() => PatchTransactionsIdMetadataRequest$inboundSchema),
  ).optional(),
});

/** @internal */
export type PatchTransactionsIdRequestBody$Outbound = {
  customerId?: string | undefined;
  amount?: string | undefined;
  currency?: string | undefined;
  provider?: string | undefined;
  providerReference?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  origin?: string | undefined;
  metadata?: PatchTransactionsIdMetadataRequest$Outbound | null | undefined;
};

/** @internal */
export const PatchTransactionsIdRequestBody$outboundSchema: z.ZodType<
  PatchTransactionsIdRequestBody$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdRequestBody
> = z.object({
  customerId: z.string().optional(),
  amount: z.string().optional(),
  currency: z.string().optional(),
  provider: z.string().optional(),
  providerReference: z.string().optional(),
  description: z.string().optional(),
  status: PatchTransactionsIdStatusRequest$outboundSchema.optional(),
  type: PatchTransactionsIdTypeRequest$outboundSchema.optional(),
  origin: PatchTransactionsIdOriginRequest$outboundSchema.optional(),
  metadata: z.nullable(
    z.lazy(() => PatchTransactionsIdMetadataRequest$outboundSchema),
  ).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdRequestBody$ {
  /** @deprecated use `PatchTransactionsIdRequestBody$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdRequestBody$inboundSchema;
  /** @deprecated use `PatchTransactionsIdRequestBody$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdRequestBody$outboundSchema;
  /** @deprecated use `PatchTransactionsIdRequestBody$Outbound` instead. */
  export type Outbound = PatchTransactionsIdRequestBody$Outbound;
}

export function patchTransactionsIdRequestBodyToJSON(
  patchTransactionsIdRequestBody: PatchTransactionsIdRequestBody,
): string {
  return JSON.stringify(
    PatchTransactionsIdRequestBody$outboundSchema.parse(
      patchTransactionsIdRequestBody,
    ),
  );
}

export function patchTransactionsIdRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdRequestBody' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdRequest$inboundSchema: z.ZodType<
  PatchTransactionsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => PatchTransactionsIdRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchTransactionsIdRequest$Outbound = {
  id: string;
  RequestBody: PatchTransactionsIdRequestBody$Outbound;
};

/** @internal */
export const PatchTransactionsIdRequest$outboundSchema: z.ZodType<
  PatchTransactionsIdRequest$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => PatchTransactionsIdRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdRequest$ {
  /** @deprecated use `PatchTransactionsIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdRequest$inboundSchema;
  /** @deprecated use `PatchTransactionsIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdRequest$outboundSchema;
  /** @deprecated use `PatchTransactionsIdRequest$Outbound` instead. */
  export type Outbound = PatchTransactionsIdRequest$Outbound;
}

export function patchTransactionsIdRequestToJSON(
  patchTransactionsIdRequest: PatchTransactionsIdRequest,
): string {
  return JSON.stringify(
    PatchTransactionsIdRequest$outboundSchema.parse(patchTransactionsIdRequest),
  );
}

export function patchTransactionsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdRequest' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdStatusResponse$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdStatusResponse
> = z.nativeEnum(PatchTransactionsIdStatusResponse);

/** @internal */
export const PatchTransactionsIdStatusResponse$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdStatusResponse
> = PatchTransactionsIdStatusResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdStatusResponse$ {
  /** @deprecated use `PatchTransactionsIdStatusResponse$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdStatusResponse$inboundSchema;
  /** @deprecated use `PatchTransactionsIdStatusResponse$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdStatusResponse$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdTypeResponse$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdTypeResponse
> = z.nativeEnum(PatchTransactionsIdTypeResponse);

/** @internal */
export const PatchTransactionsIdTypeResponse$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdTypeResponse
> = PatchTransactionsIdTypeResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdTypeResponse$ {
  /** @deprecated use `PatchTransactionsIdTypeResponse$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdTypeResponse$inboundSchema;
  /** @deprecated use `PatchTransactionsIdTypeResponse$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdTypeResponse$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdMetadataResponse$inboundSchema: z.ZodType<
  PatchTransactionsIdMetadataResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PatchTransactionsIdMetadataResponse$Outbound =
  | string
  | number
  | boolean
  | { [k: string]: any }
  | Array<any>;

/** @internal */
export const PatchTransactionsIdMetadataResponse$outboundSchema: z.ZodType<
  PatchTransactionsIdMetadataResponse$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdMetadataResponse
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdMetadataResponse$ {
  /** @deprecated use `PatchTransactionsIdMetadataResponse$inboundSchema` instead. */
  export const inboundSchema =
    PatchTransactionsIdMetadataResponse$inboundSchema;
  /** @deprecated use `PatchTransactionsIdMetadataResponse$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdMetadataResponse$outboundSchema;
  /** @deprecated use `PatchTransactionsIdMetadataResponse$Outbound` instead. */
  export type Outbound = PatchTransactionsIdMetadataResponse$Outbound;
}

export function patchTransactionsIdMetadataResponseToJSON(
  patchTransactionsIdMetadataResponse: PatchTransactionsIdMetadataResponse,
): string {
  return JSON.stringify(
    PatchTransactionsIdMetadataResponse$outboundSchema.parse(
      patchTransactionsIdMetadataResponse,
    ),
  );
}

export function patchTransactionsIdMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdMetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchTransactionsIdMetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdMetadataResponse' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdOriginResponse$inboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdOriginResponse
> = z.nativeEnum(PatchTransactionsIdOriginResponse);

/** @internal */
export const PatchTransactionsIdOriginResponse$outboundSchema: z.ZodNativeEnum<
  typeof PatchTransactionsIdOriginResponse
> = PatchTransactionsIdOriginResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdOriginResponse$ {
  /** @deprecated use `PatchTransactionsIdOriginResponse$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdOriginResponse$inboundSchema;
  /** @deprecated use `PatchTransactionsIdOriginResponse$outboundSchema` instead. */
  export const outboundSchema =
    PatchTransactionsIdOriginResponse$outboundSchema;
}

/** @internal */
export const PatchTransactionsIdData$inboundSchema: z.ZodType<
  PatchTransactionsIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: PatchTransactionsIdStatusResponse$inboundSchema,
  type: PatchTransactionsIdTypeResponse$inboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(PatchTransactionsIdOriginResponse$inboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/** @internal */
export type PatchTransactionsIdData$Outbound = {
  id: string;
  customerId: string | null;
  object: string;
  currency: string;
  fee: string | null;
  amount: string;
  provider: string;
  providerReference: string;
  description: string | null;
  status: string;
  type: string;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  origin: string | null;
  declineReason: string | null;
  createdAt: string;
  updatedAt: string;
  refundedAt: string | null;
  paidAt: string | null;
  failedAt: string | null;
  disputedAt: string | null;
};

/** @internal */
export const PatchTransactionsIdData$outboundSchema: z.ZodType<
  PatchTransactionsIdData$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdData
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  currency: z.string(),
  fee: z.nullable(z.string()),
  amount: z.string(),
  provider: z.string(),
  providerReference: z.string(),
  description: z.nullable(z.string()),
  status: PatchTransactionsIdStatusResponse$outboundSchema,
  type: PatchTransactionsIdTypeResponse$outboundSchema,
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  origin: z.nullable(PatchTransactionsIdOriginResponse$outboundSchema),
  declineReason: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  refundedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  disputedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdData$ {
  /** @deprecated use `PatchTransactionsIdData$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdData$inboundSchema;
  /** @deprecated use `PatchTransactionsIdData$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdData$outboundSchema;
  /** @deprecated use `PatchTransactionsIdData$Outbound` instead. */
  export type Outbound = PatchTransactionsIdData$Outbound;
}

export function patchTransactionsIdDataToJSON(
  patchTransactionsIdData: PatchTransactionsIdData,
): string {
  return JSON.stringify(
    PatchTransactionsIdData$outboundSchema.parse(patchTransactionsIdData),
  );
}

export function patchTransactionsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdData' from JSON`,
  );
}

/** @internal */
export const PatchTransactionsIdResponse$inboundSchema: z.ZodType<
  PatchTransactionsIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchTransactionsIdData$inboundSchema),
});

/** @internal */
export type PatchTransactionsIdResponse$Outbound = {
  success: boolean;
  data: PatchTransactionsIdData$Outbound;
};

/** @internal */
export const PatchTransactionsIdResponse$outboundSchema: z.ZodType<
  PatchTransactionsIdResponse$Outbound,
  z.ZodTypeDef,
  PatchTransactionsIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchTransactionsIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchTransactionsIdResponse$ {
  /** @deprecated use `PatchTransactionsIdResponse$inboundSchema` instead. */
  export const inboundSchema = PatchTransactionsIdResponse$inboundSchema;
  /** @deprecated use `PatchTransactionsIdResponse$outboundSchema` instead. */
  export const outboundSchema = PatchTransactionsIdResponse$outboundSchema;
  /** @deprecated use `PatchTransactionsIdResponse$Outbound` instead. */
  export type Outbound = PatchTransactionsIdResponse$Outbound;
}

export function patchTransactionsIdResponseToJSON(
  patchTransactionsIdResponse: PatchTransactionsIdResponse,
): string {
  return JSON.stringify(
    PatchTransactionsIdResponse$outboundSchema.parse(
      patchTransactionsIdResponse,
    ),
  );
}

export function patchTransactionsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchTransactionsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchTransactionsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchTransactionsIdResponse' from JSON`,
  );
}
