/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The product id
 */
export type PatchProductsIdRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
  active?: boolean | undefined;
  defaultPrice?: string | undefined;
  images?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
  url?: string | undefined;
};

export type PatchProductsIdRequest = {
  id: string;
  /**
   * The product id
   */
  requestBody: PatchProductsIdRequestBody;
};

export type PatchProductsIdImages = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PatchProductsIdMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PatchProductsIdData = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/**
 * Updated Product
 */
export type PatchProductsIdResponse = {
  success: boolean;
  data: PatchProductsIdData;
};

/** @internal */
export const PatchProductsIdRequestBody$inboundSchema: z.ZodType<
  PatchProductsIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  active: z.boolean().optional(),
  defaultPrice: z.string().optional(),
  images: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  url: z.string().optional(),
});

/** @internal */
export type PatchProductsIdRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  active?: boolean | undefined;
  defaultPrice?: string | undefined;
  images?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
  url?: string | undefined;
};

/** @internal */
export const PatchProductsIdRequestBody$outboundSchema: z.ZodType<
  PatchProductsIdRequestBody$Outbound,
  z.ZodTypeDef,
  PatchProductsIdRequestBody
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  active: z.boolean().optional(),
  defaultPrice: z.string().optional(),
  images: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  url: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdRequestBody$ {
  /** @deprecated use `PatchProductsIdRequestBody$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdRequestBody$inboundSchema;
  /** @deprecated use `PatchProductsIdRequestBody$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdRequestBody$outboundSchema;
  /** @deprecated use `PatchProductsIdRequestBody$Outbound` instead. */
  export type Outbound = PatchProductsIdRequestBody$Outbound;
}

export function patchProductsIdRequestBodyToJSON(
  patchProductsIdRequestBody: PatchProductsIdRequestBody,
): string {
  return JSON.stringify(
    PatchProductsIdRequestBody$outboundSchema.parse(patchProductsIdRequestBody),
  );
}

export function patchProductsIdRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdRequestBody' from JSON`,
  );
}

/** @internal */
export const PatchProductsIdRequest$inboundSchema: z.ZodType<
  PatchProductsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => PatchProductsIdRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchProductsIdRequest$Outbound = {
  id: string;
  RequestBody: PatchProductsIdRequestBody$Outbound;
};

/** @internal */
export const PatchProductsIdRequest$outboundSchema: z.ZodType<
  PatchProductsIdRequest$Outbound,
  z.ZodTypeDef,
  PatchProductsIdRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => PatchProductsIdRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdRequest$ {
  /** @deprecated use `PatchProductsIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdRequest$inboundSchema;
  /** @deprecated use `PatchProductsIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdRequest$outboundSchema;
  /** @deprecated use `PatchProductsIdRequest$Outbound` instead. */
  export type Outbound = PatchProductsIdRequest$Outbound;
}

export function patchProductsIdRequestToJSON(
  patchProductsIdRequest: PatchProductsIdRequest,
): string {
  return JSON.stringify(
    PatchProductsIdRequest$outboundSchema.parse(patchProductsIdRequest),
  );
}

export function patchProductsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdRequest' from JSON`,
  );
}

/** @internal */
export const PatchProductsIdImages$inboundSchema: z.ZodType<
  PatchProductsIdImages,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PatchProductsIdImages$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PatchProductsIdImages$outboundSchema: z.ZodType<
  PatchProductsIdImages$Outbound,
  z.ZodTypeDef,
  PatchProductsIdImages
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdImages$ {
  /** @deprecated use `PatchProductsIdImages$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdImages$inboundSchema;
  /** @deprecated use `PatchProductsIdImages$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdImages$outboundSchema;
  /** @deprecated use `PatchProductsIdImages$Outbound` instead. */
  export type Outbound = PatchProductsIdImages$Outbound;
}

export function patchProductsIdImagesToJSON(
  patchProductsIdImages: PatchProductsIdImages,
): string {
  return JSON.stringify(
    PatchProductsIdImages$outboundSchema.parse(patchProductsIdImages),
  );
}

export function patchProductsIdImagesFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdImages' from JSON`,
  );
}

/** @internal */
export const PatchProductsIdMetadata$inboundSchema: z.ZodType<
  PatchProductsIdMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PatchProductsIdMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PatchProductsIdMetadata$outboundSchema: z.ZodType<
  PatchProductsIdMetadata$Outbound,
  z.ZodTypeDef,
  PatchProductsIdMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdMetadata$ {
  /** @deprecated use `PatchProductsIdMetadata$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdMetadata$inboundSchema;
  /** @deprecated use `PatchProductsIdMetadata$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdMetadata$outboundSchema;
  /** @deprecated use `PatchProductsIdMetadata$Outbound` instead. */
  export type Outbound = PatchProductsIdMetadata$Outbound;
}

export function patchProductsIdMetadataToJSON(
  patchProductsIdMetadata: PatchProductsIdMetadata,
): string {
  return JSON.stringify(
    PatchProductsIdMetadata$outboundSchema.parse(patchProductsIdMetadata),
  );
}

export function patchProductsIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdMetadata' from JSON`,
  );
}

/** @internal */
export const PatchProductsIdData$inboundSchema: z.ZodType<
  PatchProductsIdData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/** @internal */
export type PatchProductsIdData$Outbound = {
  id: string;
  active: boolean;
  defaultPrice: string | null;
  name: string;
  description: string | null;
  images: string | number | boolean | { [k: string]: any } | Array<any> | null;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  livemode: boolean;
  url: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/** @internal */
export const PatchProductsIdData$outboundSchema: z.ZodType<
  PatchProductsIdData$Outbound,
  z.ZodTypeDef,
  PatchProductsIdData
> = z.object({
  id: z.string(),
  active: z.boolean(),
  defaultPrice: z.nullable(z.string()),
  name: z.string(),
  description: z.nullable(z.string()),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ),
  livemode: z.boolean(),
  url: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdData$ {
  /** @deprecated use `PatchProductsIdData$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdData$inboundSchema;
  /** @deprecated use `PatchProductsIdData$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdData$outboundSchema;
  /** @deprecated use `PatchProductsIdData$Outbound` instead. */
  export type Outbound = PatchProductsIdData$Outbound;
}

export function patchProductsIdDataToJSON(
  patchProductsIdData: PatchProductsIdData,
): string {
  return JSON.stringify(
    PatchProductsIdData$outboundSchema.parse(patchProductsIdData),
  );
}

export function patchProductsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdData' from JSON`,
  );
}

/** @internal */
export const PatchProductsIdResponse$inboundSchema: z.ZodType<
  PatchProductsIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchProductsIdData$inboundSchema),
});

/** @internal */
export type PatchProductsIdResponse$Outbound = {
  success: boolean;
  data: PatchProductsIdData$Outbound;
};

/** @internal */
export const PatchProductsIdResponse$outboundSchema: z.ZodType<
  PatchProductsIdResponse$Outbound,
  z.ZodTypeDef,
  PatchProductsIdResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PatchProductsIdData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchProductsIdResponse$ {
  /** @deprecated use `PatchProductsIdResponse$inboundSchema` instead. */
  export const inboundSchema = PatchProductsIdResponse$inboundSchema;
  /** @deprecated use `PatchProductsIdResponse$outboundSchema` instead. */
  export const outboundSchema = PatchProductsIdResponse$outboundSchema;
  /** @deprecated use `PatchProductsIdResponse$Outbound` instead. */
  export type Outbound = PatchProductsIdResponse$Outbound;
}

export function patchProductsIdResponseToJSON(
  patchProductsIdResponse: PatchProductsIdResponse,
): string {
  return JSON.stringify(
    PatchProductsIdResponse$outboundSchema.parse(patchProductsIdResponse),
  );
}

export function patchProductsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchProductsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchProductsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchProductsIdResponse' from JSON`,
  );
}
