/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The customer to create
 */
export type PostCustomersRequest = {
  name: string;
  email: string;
  phoneNumber?: string | undefined;
  description?: string | undefined;
  balance?: string | undefined;
};

export type PostCustomersMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PostCustomersData = {
  name?: string | null | undefined;
  description?: string | null | undefined;
  balance?: string | undefined;
  livemode?: boolean | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  currency?: string | undefined;
  email?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | null | undefined;
  lastActiveAt?: string | null | undefined;
};

/**
 * Create a Customer
 */
export type PostCustomersResponse = {
  success: boolean;
  data: PostCustomersData;
};

/** @internal */
export const PostCustomersRequest$inboundSchema: z.ZodType<
  PostCustomersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  email: z.string(),
  phoneNumber: z.string().optional(),
  description: z.string().optional(),
  balance: z.string().optional(),
});

/** @internal */
export type PostCustomersRequest$Outbound = {
  name: string;
  email: string;
  phoneNumber?: string | undefined;
  description?: string | undefined;
  balance?: string | undefined;
};

/** @internal */
export const PostCustomersRequest$outboundSchema: z.ZodType<
  PostCustomersRequest$Outbound,
  z.ZodTypeDef,
  PostCustomersRequest
> = z.object({
  name: z.string(),
  email: z.string(),
  phoneNumber: z.string().optional(),
  description: z.string().optional(),
  balance: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostCustomersRequest$ {
  /** @deprecated use `PostCustomersRequest$inboundSchema` instead. */
  export const inboundSchema = PostCustomersRequest$inboundSchema;
  /** @deprecated use `PostCustomersRequest$outboundSchema` instead. */
  export const outboundSchema = PostCustomersRequest$outboundSchema;
  /** @deprecated use `PostCustomersRequest$Outbound` instead. */
  export type Outbound = PostCustomersRequest$Outbound;
}

export function postCustomersRequestToJSON(
  postCustomersRequest: PostCustomersRequest,
): string {
  return JSON.stringify(
    PostCustomersRequest$outboundSchema.parse(postCustomersRequest),
  );
}

export function postCustomersRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostCustomersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostCustomersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostCustomersRequest' from JSON`,
  );
}

/** @internal */
export const PostCustomersMetadata$inboundSchema: z.ZodType<
  PostCustomersMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PostCustomersMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PostCustomersMetadata$outboundSchema: z.ZodType<
  PostCustomersMetadata$Outbound,
  z.ZodTypeDef,
  PostCustomersMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostCustomersMetadata$ {
  /** @deprecated use `PostCustomersMetadata$inboundSchema` instead. */
  export const inboundSchema = PostCustomersMetadata$inboundSchema;
  /** @deprecated use `PostCustomersMetadata$outboundSchema` instead. */
  export const outboundSchema = PostCustomersMetadata$outboundSchema;
  /** @deprecated use `PostCustomersMetadata$Outbound` instead. */
  export type Outbound = PostCustomersMetadata$Outbound;
}

export function postCustomersMetadataToJSON(
  postCustomersMetadata: PostCustomersMetadata,
): string {
  return JSON.stringify(
    PostCustomersMetadata$outboundSchema.parse(postCustomersMetadata),
  );
}

export function postCustomersMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PostCustomersMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostCustomersMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostCustomersMetadata' from JSON`,
  );
}

/** @internal */
export const PostCustomersData$inboundSchema: z.ZodType<
  PostCustomersData,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  balance: z.string().optional(),
  livemode: z.boolean().optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  currency: z.string().optional(),
  email: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.nullable(z.string()).optional(),
  lastActiveAt: z.nullable(z.string()).optional(),
});

/** @internal */
export type PostCustomersData$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
  balance?: string | undefined;
  livemode?: boolean | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  currency?: string | undefined;
  email?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | null | undefined;
  lastActiveAt?: string | null | undefined;
};

/** @internal */
export const PostCustomersData$outboundSchema: z.ZodType<
  PostCustomersData$Outbound,
  z.ZodTypeDef,
  PostCustomersData
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  balance: z.string().optional(),
  livemode: z.boolean().optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  currency: z.string().optional(),
  email: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.nullable(z.string()).optional(),
  lastActiveAt: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostCustomersData$ {
  /** @deprecated use `PostCustomersData$inboundSchema` instead. */
  export const inboundSchema = PostCustomersData$inboundSchema;
  /** @deprecated use `PostCustomersData$outboundSchema` instead. */
  export const outboundSchema = PostCustomersData$outboundSchema;
  /** @deprecated use `PostCustomersData$Outbound` instead. */
  export type Outbound = PostCustomersData$Outbound;
}

export function postCustomersDataToJSON(
  postCustomersData: PostCustomersData,
): string {
  return JSON.stringify(
    PostCustomersData$outboundSchema.parse(postCustomersData),
  );
}

export function postCustomersDataFromJSON(
  jsonString: string,
): SafeParseResult<PostCustomersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostCustomersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostCustomersData' from JSON`,
  );
}

/** @internal */
export const PostCustomersResponse$inboundSchema: z.ZodType<
  PostCustomersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostCustomersData$inboundSchema),
});

/** @internal */
export type PostCustomersResponse$Outbound = {
  success: boolean;
  data: PostCustomersData$Outbound;
};

/** @internal */
export const PostCustomersResponse$outboundSchema: z.ZodType<
  PostCustomersResponse$Outbound,
  z.ZodTypeDef,
  PostCustomersResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostCustomersData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostCustomersResponse$ {
  /** @deprecated use `PostCustomersResponse$inboundSchema` instead. */
  export const inboundSchema = PostCustomersResponse$inboundSchema;
  /** @deprecated use `PostCustomersResponse$outboundSchema` instead. */
  export const outboundSchema = PostCustomersResponse$outboundSchema;
  /** @deprecated use `PostCustomersResponse$Outbound` instead. */
  export type Outbound = PostCustomersResponse$Outbound;
}

export function postCustomersResponseToJSON(
  postCustomersResponse: PostCustomersResponse,
): string {
  return JSON.stringify(
    PostCustomersResponse$outboundSchema.parse(postCustomersResponse),
  );
}

export function postCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostCustomersResponse' from JSON`,
  );
}
