/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The payment details
 */
export type PostPayMpesaRequest = {
  phoneNumber: string;
  amount: string;
  transactionDesc: string;
  accountReference?: string | undefined;
};

export type PostPayMpesaData = {
  checkoutRequestID: string;
  customerMessage: string;
  merchantRequestID: string;
  responseCode: string;
  responseDescription: string;
};

/**
 * Payment initiated
 */
export type PostPayMpesaResponse = {
  success: boolean;
  data: PostPayMpesaData;
};

/** @internal */
export const PostPayMpesaRequest$inboundSchema: z.ZodType<
  PostPayMpesaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  phoneNumber: z.string(),
  amount: z.string(),
  transactionDesc: z.string(),
  accountReference: z.string().optional(),
});

/** @internal */
export type PostPayMpesaRequest$Outbound = {
  phoneNumber: string;
  amount: string;
  transactionDesc: string;
  accountReference?: string | undefined;
};

/** @internal */
export const PostPayMpesaRequest$outboundSchema: z.ZodType<
  PostPayMpesaRequest$Outbound,
  z.ZodTypeDef,
  PostPayMpesaRequest
> = z.object({
  phoneNumber: z.string(),
  amount: z.string(),
  transactionDesc: z.string(),
  accountReference: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostPayMpesaRequest$ {
  /** @deprecated use `PostPayMpesaRequest$inboundSchema` instead. */
  export const inboundSchema = PostPayMpesaRequest$inboundSchema;
  /** @deprecated use `PostPayMpesaRequest$outboundSchema` instead. */
  export const outboundSchema = PostPayMpesaRequest$outboundSchema;
  /** @deprecated use `PostPayMpesaRequest$Outbound` instead. */
  export type Outbound = PostPayMpesaRequest$Outbound;
}

export function postPayMpesaRequestToJSON(
  postPayMpesaRequest: PostPayMpesaRequest,
): string {
  return JSON.stringify(
    PostPayMpesaRequest$outboundSchema.parse(postPayMpesaRequest),
  );
}

export function postPayMpesaRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostPayMpesaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostPayMpesaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostPayMpesaRequest' from JSON`,
  );
}

/** @internal */
export const PostPayMpesaData$inboundSchema: z.ZodType<
  PostPayMpesaData,
  z.ZodTypeDef,
  unknown
> = z.object({
  CheckoutRequestID: z.string(),
  CustomerMessage: z.string(),
  MerchantRequestID: z.string(),
  ResponseCode: z.string(),
  ResponseDescription: z.string(),
}).transform((v) => {
  return remap$(v, {
    "CheckoutRequestID": "checkoutRequestID",
    "CustomerMessage": "customerMessage",
    "MerchantRequestID": "merchantRequestID",
    "ResponseCode": "responseCode",
    "ResponseDescription": "responseDescription",
  });
});

/** @internal */
export type PostPayMpesaData$Outbound = {
  CheckoutRequestID: string;
  CustomerMessage: string;
  MerchantRequestID: string;
  ResponseCode: string;
  ResponseDescription: string;
};

/** @internal */
export const PostPayMpesaData$outboundSchema: z.ZodType<
  PostPayMpesaData$Outbound,
  z.ZodTypeDef,
  PostPayMpesaData
> = z.object({
  checkoutRequestID: z.string(),
  customerMessage: z.string(),
  merchantRequestID: z.string(),
  responseCode: z.string(),
  responseDescription: z.string(),
}).transform((v) => {
  return remap$(v, {
    checkoutRequestID: "CheckoutRequestID",
    customerMessage: "CustomerMessage",
    merchantRequestID: "MerchantRequestID",
    responseCode: "ResponseCode",
    responseDescription: "ResponseDescription",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostPayMpesaData$ {
  /** @deprecated use `PostPayMpesaData$inboundSchema` instead. */
  export const inboundSchema = PostPayMpesaData$inboundSchema;
  /** @deprecated use `PostPayMpesaData$outboundSchema` instead. */
  export const outboundSchema = PostPayMpesaData$outboundSchema;
  /** @deprecated use `PostPayMpesaData$Outbound` instead. */
  export type Outbound = PostPayMpesaData$Outbound;
}

export function postPayMpesaDataToJSON(
  postPayMpesaData: PostPayMpesaData,
): string {
  return JSON.stringify(
    PostPayMpesaData$outboundSchema.parse(postPayMpesaData),
  );
}

export function postPayMpesaDataFromJSON(
  jsonString: string,
): SafeParseResult<PostPayMpesaData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostPayMpesaData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostPayMpesaData' from JSON`,
  );
}

/** @internal */
export const PostPayMpesaResponse$inboundSchema: z.ZodType<
  PostPayMpesaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostPayMpesaData$inboundSchema),
});

/** @internal */
export type PostPayMpesaResponse$Outbound = {
  success: boolean;
  data: PostPayMpesaData$Outbound;
};

/** @internal */
export const PostPayMpesaResponse$outboundSchema: z.ZodType<
  PostPayMpesaResponse$Outbound,
  z.ZodTypeDef,
  PostPayMpesaResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostPayMpesaData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostPayMpesaResponse$ {
  /** @deprecated use `PostPayMpesaResponse$inboundSchema` instead. */
  export const inboundSchema = PostPayMpesaResponse$inboundSchema;
  /** @deprecated use `PostPayMpesaResponse$outboundSchema` instead. */
  export const outboundSchema = PostPayMpesaResponse$outboundSchema;
  /** @deprecated use `PostPayMpesaResponse$Outbound` instead. */
  export type Outbound = PostPayMpesaResponse$Outbound;
}

export function postPayMpesaResponseToJSON(
  postPayMpesaResponse: PostPayMpesaResponse,
): string {
  return JSON.stringify(
    PostPayMpesaResponse$outboundSchema.parse(postPayMpesaResponse),
  );
}

export function postPayMpesaResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostPayMpesaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostPayMpesaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostPayMpesaResponse' from JSON`,
  );
}
