/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The product to create
 */
export type PostProductsRequest = {
  name: string;
  description?: string | undefined;
  active?: boolean | undefined;
  defaultPrice?: string | undefined;
  images?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
  url?: string | undefined;
};

export type PostProductsImages = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PostProductsMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type PostProductsData = {
  active?: boolean | undefined;
  defaultPrice?: string | null | undefined;
  name: string;
  description?: string | null | undefined;
  images?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  livemode?: boolean | undefined;
  url?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | null | undefined;
};

/**
 * Create a Product
 */
export type PostProductsResponse = {
  success: boolean;
  data: PostProductsData;
};

/** @internal */
export const PostProductsRequest$inboundSchema: z.ZodType<
  PostProductsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  active: z.boolean().default(true),
  defaultPrice: z.string().optional(),
  images: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  url: z.string().optional(),
});

/** @internal */
export type PostProductsRequest$Outbound = {
  name: string;
  description?: string | undefined;
  active: boolean;
  defaultPrice?: string | undefined;
  images?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
  url?: string | undefined;
};

/** @internal */
export const PostProductsRequest$outboundSchema: z.ZodType<
  PostProductsRequest$Outbound,
  z.ZodTypeDef,
  PostProductsRequest
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  active: z.boolean().default(true),
  defaultPrice: z.string().optional(),
  images: z.array(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  url: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostProductsRequest$ {
  /** @deprecated use `PostProductsRequest$inboundSchema` instead. */
  export const inboundSchema = PostProductsRequest$inboundSchema;
  /** @deprecated use `PostProductsRequest$outboundSchema` instead. */
  export const outboundSchema = PostProductsRequest$outboundSchema;
  /** @deprecated use `PostProductsRequest$Outbound` instead. */
  export type Outbound = PostProductsRequest$Outbound;
}

export function postProductsRequestToJSON(
  postProductsRequest: PostProductsRequest,
): string {
  return JSON.stringify(
    PostProductsRequest$outboundSchema.parse(postProductsRequest),
  );
}

export function postProductsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostProductsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProductsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProductsRequest' from JSON`,
  );
}

/** @internal */
export const PostProductsImages$inboundSchema: z.ZodType<
  PostProductsImages,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PostProductsImages$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PostProductsImages$outboundSchema: z.ZodType<
  PostProductsImages$Outbound,
  z.ZodTypeDef,
  PostProductsImages
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostProductsImages$ {
  /** @deprecated use `PostProductsImages$inboundSchema` instead. */
  export const inboundSchema = PostProductsImages$inboundSchema;
  /** @deprecated use `PostProductsImages$outboundSchema` instead. */
  export const outboundSchema = PostProductsImages$outboundSchema;
  /** @deprecated use `PostProductsImages$Outbound` instead. */
  export type Outbound = PostProductsImages$Outbound;
}

export function postProductsImagesToJSON(
  postProductsImages: PostProductsImages,
): string {
  return JSON.stringify(
    PostProductsImages$outboundSchema.parse(postProductsImages),
  );
}

export function postProductsImagesFromJSON(
  jsonString: string,
): SafeParseResult<PostProductsImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProductsImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProductsImages' from JSON`,
  );
}

/** @internal */
export const PostProductsMetadata$inboundSchema: z.ZodType<
  PostProductsMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PostProductsMetadata$Outbound = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/** @internal */
export const PostProductsMetadata$outboundSchema: z.ZodType<
  PostProductsMetadata$Outbound,
  z.ZodTypeDef,
  PostProductsMetadata
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostProductsMetadata$ {
  /** @deprecated use `PostProductsMetadata$inboundSchema` instead. */
  export const inboundSchema = PostProductsMetadata$inboundSchema;
  /** @deprecated use `PostProductsMetadata$outboundSchema` instead. */
  export const outboundSchema = PostProductsMetadata$outboundSchema;
  /** @deprecated use `PostProductsMetadata$Outbound` instead. */
  export type Outbound = PostProductsMetadata$Outbound;
}

export function postProductsMetadataToJSON(
  postProductsMetadata: PostProductsMetadata,
): string {
  return JSON.stringify(
    PostProductsMetadata$outboundSchema.parse(postProductsMetadata),
  );
}

export function postProductsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PostProductsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProductsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProductsMetadata' from JSON`,
  );
}

/** @internal */
export const PostProductsData$inboundSchema: z.ZodType<
  PostProductsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  active: z.boolean().optional(),
  defaultPrice: z.nullable(z.string()).optional(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  livemode: z.boolean().optional(),
  url: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.nullable(z.string()).optional(),
});

/** @internal */
export type PostProductsData$Outbound = {
  active?: boolean | undefined;
  defaultPrice?: string | null | undefined;
  name: string;
  description?: string | null | undefined;
  images?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  livemode?: boolean | undefined;
  url?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | null | undefined;
};

/** @internal */
export const PostProductsData$outboundSchema: z.ZodType<
  PostProductsData$Outbound,
  z.ZodTypeDef,
  PostProductsData
> = z.object({
  active: z.boolean().optional(),
  defaultPrice: z.nullable(z.string()).optional(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  images: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  livemode: z.boolean().optional(),
  url: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostProductsData$ {
  /** @deprecated use `PostProductsData$inboundSchema` instead. */
  export const inboundSchema = PostProductsData$inboundSchema;
  /** @deprecated use `PostProductsData$outboundSchema` instead. */
  export const outboundSchema = PostProductsData$outboundSchema;
  /** @deprecated use `PostProductsData$Outbound` instead. */
  export type Outbound = PostProductsData$Outbound;
}

export function postProductsDataToJSON(
  postProductsData: PostProductsData,
): string {
  return JSON.stringify(
    PostProductsData$outboundSchema.parse(postProductsData),
  );
}

export function postProductsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostProductsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProductsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProductsData' from JSON`,
  );
}

/** @internal */
export const PostProductsResponse$inboundSchema: z.ZodType<
  PostProductsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostProductsData$inboundSchema),
});

/** @internal */
export type PostProductsResponse$Outbound = {
  success: boolean;
  data: PostProductsData$Outbound;
};

/** @internal */
export const PostProductsResponse$outboundSchema: z.ZodType<
  PostProductsResponse$Outbound,
  z.ZodTypeDef,
  PostProductsResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostProductsData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostProductsResponse$ {
  /** @deprecated use `PostProductsResponse$inboundSchema` instead. */
  export const inboundSchema = PostProductsResponse$inboundSchema;
  /** @deprecated use `PostProductsResponse$outboundSchema` instead. */
  export const outboundSchema = PostProductsResponse$outboundSchema;
  /** @deprecated use `PostProductsResponse$Outbound` instead. */
  export type Outbound = PostProductsResponse$Outbound;
}

export function postProductsResponseToJSON(
  postProductsResponse: PostProductsResponse,
): string {
  return JSON.stringify(
    PostProductsResponse$outboundSchema.parse(postProductsResponse),
  );
}

export function postProductsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostProductsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProductsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProductsResponse' from JSON`,
  );
}
