/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostTransactionsStatusRequest = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type PostTransactionsStatusRequest = ClosedEnum<
  typeof PostTransactionsStatusRequest
>;

export const PostTransactionsTypeRequest = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type PostTransactionsTypeRequest = ClosedEnum<
  typeof PostTransactionsTypeRequest
>;

export const PostTransactionsOriginRequest = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type PostTransactionsOriginRequest = ClosedEnum<
  typeof PostTransactionsOriginRequest
>;

export const PostTransactionsProvider = {
  Mpesa: "mpesa",
} as const;
export type PostTransactionsProvider = ClosedEnum<
  typeof PostTransactionsProvider
>;

export type PostTransactionsInitialRequest = {
  merchantRequestId: string | null;
  checkoutRequestId: string | null;
  responseCode: string | null;
  responseDescription: string | null;
  customerMessage: string | null;
};

export type PostTransactionsCallbackResult = {
  resultCode: number | null;
  resultDescription: string | null;
  receiptNumber: string | null;
  amount: number | null;
  transactionDate: string | null;
  phoneNumber: string | null;
};

export type PostTransactionsMetadataRequest = {
  provider: PostTransactionsProvider;
  initialRequest: PostTransactionsInitialRequest;
  callbackResult: PostTransactionsCallbackResult;
};

/**
 * The transaction to create
 */
export type PostTransactionsRequest = {
  customerId: string;
  amount: string;
  currency?: string | undefined;
  provider?: string | undefined;
  providerReference: string;
  description?: string | undefined;
  status?: PostTransactionsStatusRequest | undefined;
  type?: PostTransactionsTypeRequest | undefined;
  origin?: PostTransactionsOriginRequest | undefined;
  metadata?: PostTransactionsMetadataRequest | null | undefined;
};

export const PostTransactionsStatusResponse = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Refunded: "refunded",
} as const;
export type PostTransactionsStatusResponse = ClosedEnum<
  typeof PostTransactionsStatusResponse
>;

export const PostTransactionsTypeResponse = {
  Payment: "payment",
  Donation: "donation",
} as const;
export type PostTransactionsTypeResponse = ClosedEnum<
  typeof PostTransactionsTypeResponse
>;

export type PostTransactionsMetadataResponse = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export const PostTransactionsOriginResponse = {
  Web: "web",
  Mobile: "mobile",
  Api: "api",
} as const;
export type PostTransactionsOriginResponse = ClosedEnum<
  typeof PostTransactionsOriginResponse
>;

export type PostTransactionsData = {
  customerId?: string | null | undefined;
  object?: string | undefined;
  currency?: string | undefined;
  fee?: string | null | undefined;
  amount: string;
  provider?: string | undefined;
  providerReference: string;
  description?: string | null | undefined;
  status?: PostTransactionsStatusResponse | undefined;
  type?: PostTransactionsTypeResponse | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  origin?: PostTransactionsOriginResponse | null | undefined;
  declineReason?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  refundedAt?: string | null | undefined;
  paidAt?: string | null | undefined;
  failedAt?: string | null | undefined;
  disputedAt?: string | null | undefined;
};

/**
 * Create a Transaction
 */
export type PostTransactionsResponse = {
  success: boolean;
  data: PostTransactionsData;
};

/** @internal */
export const PostTransactionsStatusRequest$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsStatusRequest
> = z.nativeEnum(PostTransactionsStatusRequest);

/** @internal */
export const PostTransactionsStatusRequest$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsStatusRequest
> = PostTransactionsStatusRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsStatusRequest$ {
  /** @deprecated use `PostTransactionsStatusRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsStatusRequest$inboundSchema;
  /** @deprecated use `PostTransactionsStatusRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsStatusRequest$outboundSchema;
}

/** @internal */
export const PostTransactionsTypeRequest$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsTypeRequest
> = z.nativeEnum(PostTransactionsTypeRequest);

/** @internal */
export const PostTransactionsTypeRequest$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsTypeRequest
> = PostTransactionsTypeRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsTypeRequest$ {
  /** @deprecated use `PostTransactionsTypeRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsTypeRequest$inboundSchema;
  /** @deprecated use `PostTransactionsTypeRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsTypeRequest$outboundSchema;
}

/** @internal */
export const PostTransactionsOriginRequest$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsOriginRequest
> = z.nativeEnum(PostTransactionsOriginRequest);

/** @internal */
export const PostTransactionsOriginRequest$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsOriginRequest
> = PostTransactionsOriginRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsOriginRequest$ {
  /** @deprecated use `PostTransactionsOriginRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsOriginRequest$inboundSchema;
  /** @deprecated use `PostTransactionsOriginRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsOriginRequest$outboundSchema;
}

/** @internal */
export const PostTransactionsProvider$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsProvider
> = z.nativeEnum(PostTransactionsProvider);

/** @internal */
export const PostTransactionsProvider$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsProvider
> = PostTransactionsProvider$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsProvider$ {
  /** @deprecated use `PostTransactionsProvider$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsProvider$inboundSchema;
  /** @deprecated use `PostTransactionsProvider$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsProvider$outboundSchema;
}

/** @internal */
export const PostTransactionsInitialRequest$inboundSchema: z.ZodType<
  PostTransactionsInitialRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  responseCode: z.nullable(z.string()),
  responseDescription: z.nullable(z.string()),
  customerMessage: z.nullable(z.string()),
});

/** @internal */
export type PostTransactionsInitialRequest$Outbound = {
  merchantRequestId: string | null;
  checkoutRequestId: string | null;
  responseCode: string | null;
  responseDescription: string | null;
  customerMessage: string | null;
};

/** @internal */
export const PostTransactionsInitialRequest$outboundSchema: z.ZodType<
  PostTransactionsInitialRequest$Outbound,
  z.ZodTypeDef,
  PostTransactionsInitialRequest
> = z.object({
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  responseCode: z.nullable(z.string()),
  responseDescription: z.nullable(z.string()),
  customerMessage: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsInitialRequest$ {
  /** @deprecated use `PostTransactionsInitialRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsInitialRequest$inboundSchema;
  /** @deprecated use `PostTransactionsInitialRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsInitialRequest$outboundSchema;
  /** @deprecated use `PostTransactionsInitialRequest$Outbound` instead. */
  export type Outbound = PostTransactionsInitialRequest$Outbound;
}

export function postTransactionsInitialRequestToJSON(
  postTransactionsInitialRequest: PostTransactionsInitialRequest,
): string {
  return JSON.stringify(
    PostTransactionsInitialRequest$outboundSchema.parse(
      postTransactionsInitialRequest,
    ),
  );
}

export function postTransactionsInitialRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsInitialRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsInitialRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsInitialRequest' from JSON`,
  );
}

/** @internal */
export const PostTransactionsCallbackResult$inboundSchema: z.ZodType<
  PostTransactionsCallbackResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.nullable(z.number()),
  resultDescription: z.nullable(z.string()),
  receiptNumber: z.nullable(z.string()),
  amount: z.nullable(z.number()),
  transactionDate: z.nullable(z.string()),
  phoneNumber: z.nullable(z.string()),
});

/** @internal */
export type PostTransactionsCallbackResult$Outbound = {
  resultCode: number | null;
  resultDescription: string | null;
  receiptNumber: string | null;
  amount: number | null;
  transactionDate: string | null;
  phoneNumber: string | null;
};

/** @internal */
export const PostTransactionsCallbackResult$outboundSchema: z.ZodType<
  PostTransactionsCallbackResult$Outbound,
  z.ZodTypeDef,
  PostTransactionsCallbackResult
> = z.object({
  resultCode: z.nullable(z.number()),
  resultDescription: z.nullable(z.string()),
  receiptNumber: z.nullable(z.string()),
  amount: z.nullable(z.number()),
  transactionDate: z.nullable(z.string()),
  phoneNumber: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsCallbackResult$ {
  /** @deprecated use `PostTransactionsCallbackResult$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsCallbackResult$inboundSchema;
  /** @deprecated use `PostTransactionsCallbackResult$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsCallbackResult$outboundSchema;
  /** @deprecated use `PostTransactionsCallbackResult$Outbound` instead. */
  export type Outbound = PostTransactionsCallbackResult$Outbound;
}

export function postTransactionsCallbackResultToJSON(
  postTransactionsCallbackResult: PostTransactionsCallbackResult,
): string {
  return JSON.stringify(
    PostTransactionsCallbackResult$outboundSchema.parse(
      postTransactionsCallbackResult,
    ),
  );
}

export function postTransactionsCallbackResultFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsCallbackResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsCallbackResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsCallbackResult' from JSON`,
  );
}

/** @internal */
export const PostTransactionsMetadataRequest$inboundSchema: z.ZodType<
  PostTransactionsMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  provider: PostTransactionsProvider$inboundSchema,
  initialRequest: z.lazy(() => PostTransactionsInitialRequest$inboundSchema),
  callbackResult: z.lazy(() => PostTransactionsCallbackResult$inboundSchema),
});

/** @internal */
export type PostTransactionsMetadataRequest$Outbound = {
  provider: string;
  initialRequest: PostTransactionsInitialRequest$Outbound;
  callbackResult: PostTransactionsCallbackResult$Outbound;
};

/** @internal */
export const PostTransactionsMetadataRequest$outboundSchema: z.ZodType<
  PostTransactionsMetadataRequest$Outbound,
  z.ZodTypeDef,
  PostTransactionsMetadataRequest
> = z.object({
  provider: PostTransactionsProvider$outboundSchema,
  initialRequest: z.lazy(() => PostTransactionsInitialRequest$outboundSchema),
  callbackResult: z.lazy(() => PostTransactionsCallbackResult$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsMetadataRequest$ {
  /** @deprecated use `PostTransactionsMetadataRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsMetadataRequest$inboundSchema;
  /** @deprecated use `PostTransactionsMetadataRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsMetadataRequest$outboundSchema;
  /** @deprecated use `PostTransactionsMetadataRequest$Outbound` instead. */
  export type Outbound = PostTransactionsMetadataRequest$Outbound;
}

export function postTransactionsMetadataRequestToJSON(
  postTransactionsMetadataRequest: PostTransactionsMetadataRequest,
): string {
  return JSON.stringify(
    PostTransactionsMetadataRequest$outboundSchema.parse(
      postTransactionsMetadataRequest,
    ),
  );
}

export function postTransactionsMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsMetadataRequest' from JSON`,
  );
}

/** @internal */
export const PostTransactionsRequest$inboundSchema: z.ZodType<
  PostTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string(),
  amount: z.string(),
  currency: z.string().default("kes"),
  provider: z.string().default("mpesa"),
  providerReference: z.string(),
  description: z.string().optional(),
  status: PostTransactionsStatusRequest$inboundSchema.default("pending"),
  type: PostTransactionsTypeRequest$inboundSchema.default("payment"),
  origin: PostTransactionsOriginRequest$inboundSchema.default("api"),
  metadata: z.nullable(
    z.lazy(() => PostTransactionsMetadataRequest$inboundSchema),
  ).optional(),
});

/** @internal */
export type PostTransactionsRequest$Outbound = {
  customerId: string;
  amount: string;
  currency: string;
  provider: string;
  providerReference: string;
  description?: string | undefined;
  status: string;
  type: string;
  origin: string;
  metadata?: PostTransactionsMetadataRequest$Outbound | null | undefined;
};

/** @internal */
export const PostTransactionsRequest$outboundSchema: z.ZodType<
  PostTransactionsRequest$Outbound,
  z.ZodTypeDef,
  PostTransactionsRequest
> = z.object({
  customerId: z.string(),
  amount: z.string(),
  currency: z.string().default("kes"),
  provider: z.string().default("mpesa"),
  providerReference: z.string(),
  description: z.string().optional(),
  status: PostTransactionsStatusRequest$outboundSchema.default("pending"),
  type: PostTransactionsTypeRequest$outboundSchema.default("payment"),
  origin: PostTransactionsOriginRequest$outboundSchema.default("api"),
  metadata: z.nullable(
    z.lazy(() => PostTransactionsMetadataRequest$outboundSchema),
  ).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsRequest$ {
  /** @deprecated use `PostTransactionsRequest$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsRequest$inboundSchema;
  /** @deprecated use `PostTransactionsRequest$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsRequest$outboundSchema;
  /** @deprecated use `PostTransactionsRequest$Outbound` instead. */
  export type Outbound = PostTransactionsRequest$Outbound;
}

export function postTransactionsRequestToJSON(
  postTransactionsRequest: PostTransactionsRequest,
): string {
  return JSON.stringify(
    PostTransactionsRequest$outboundSchema.parse(postTransactionsRequest),
  );
}

export function postTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsRequest' from JSON`,
  );
}

/** @internal */
export const PostTransactionsStatusResponse$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsStatusResponse
> = z.nativeEnum(PostTransactionsStatusResponse);

/** @internal */
export const PostTransactionsStatusResponse$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsStatusResponse
> = PostTransactionsStatusResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsStatusResponse$ {
  /** @deprecated use `PostTransactionsStatusResponse$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsStatusResponse$inboundSchema;
  /** @deprecated use `PostTransactionsStatusResponse$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsStatusResponse$outboundSchema;
}

/** @internal */
export const PostTransactionsTypeResponse$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsTypeResponse
> = z.nativeEnum(PostTransactionsTypeResponse);

/** @internal */
export const PostTransactionsTypeResponse$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsTypeResponse
> = PostTransactionsTypeResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsTypeResponse$ {
  /** @deprecated use `PostTransactionsTypeResponse$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsTypeResponse$inboundSchema;
  /** @deprecated use `PostTransactionsTypeResponse$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsTypeResponse$outboundSchema;
}

/** @internal */
export const PostTransactionsMetadataResponse$inboundSchema: z.ZodType<
  PostTransactionsMetadataResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/** @internal */
export type PostTransactionsMetadataResponse$Outbound =
  | string
  | number
  | boolean
  | { [k: string]: any }
  | Array<any>;

/** @internal */
export const PostTransactionsMetadataResponse$outboundSchema: z.ZodType<
  PostTransactionsMetadataResponse$Outbound,
  z.ZodTypeDef,
  PostTransactionsMetadataResponse
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsMetadataResponse$ {
  /** @deprecated use `PostTransactionsMetadataResponse$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsMetadataResponse$inboundSchema;
  /** @deprecated use `PostTransactionsMetadataResponse$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsMetadataResponse$outboundSchema;
  /** @deprecated use `PostTransactionsMetadataResponse$Outbound` instead. */
  export type Outbound = PostTransactionsMetadataResponse$Outbound;
}

export function postTransactionsMetadataResponseToJSON(
  postTransactionsMetadataResponse: PostTransactionsMetadataResponse,
): string {
  return JSON.stringify(
    PostTransactionsMetadataResponse$outboundSchema.parse(
      postTransactionsMetadataResponse,
    ),
  );
}

export function postTransactionsMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsMetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsMetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsMetadataResponse' from JSON`,
  );
}

/** @internal */
export const PostTransactionsOriginResponse$inboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsOriginResponse
> = z.nativeEnum(PostTransactionsOriginResponse);

/** @internal */
export const PostTransactionsOriginResponse$outboundSchema: z.ZodNativeEnum<
  typeof PostTransactionsOriginResponse
> = PostTransactionsOriginResponse$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsOriginResponse$ {
  /** @deprecated use `PostTransactionsOriginResponse$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsOriginResponse$inboundSchema;
  /** @deprecated use `PostTransactionsOriginResponse$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsOriginResponse$outboundSchema;
}

/** @internal */
export const PostTransactionsData$inboundSchema: z.ZodType<
  PostTransactionsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.nullable(z.string()).optional(),
  object: z.string().optional(),
  currency: z.string().optional(),
  fee: z.nullable(z.string()).optional(),
  amount: z.string(),
  provider: z.string().optional(),
  providerReference: z.string(),
  description: z.nullable(z.string()).optional(),
  status: PostTransactionsStatusResponse$inboundSchema.optional(),
  type: PostTransactionsTypeResponse$inboundSchema.optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  origin: z.nullable(PostTransactionsOriginResponse$inboundSchema).optional(),
  declineReason: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  refundedAt: z.nullable(z.string()).optional(),
  paidAt: z.nullable(z.string()).optional(),
  failedAt: z.nullable(z.string()).optional(),
  disputedAt: z.nullable(z.string()).optional(),
});

/** @internal */
export type PostTransactionsData$Outbound = {
  customerId?: string | null | undefined;
  object?: string | undefined;
  currency?: string | undefined;
  fee?: string | null | undefined;
  amount: string;
  provider?: string | undefined;
  providerReference: string;
  description?: string | null | undefined;
  status?: string | undefined;
  type?: string | undefined;
  metadata?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null
    | undefined;
  origin?: string | null | undefined;
  declineReason?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  refundedAt?: string | null | undefined;
  paidAt?: string | null | undefined;
  failedAt?: string | null | undefined;
  disputedAt?: string | null | undefined;
};

/** @internal */
export const PostTransactionsData$outboundSchema: z.ZodType<
  PostTransactionsData$Outbound,
  z.ZodTypeDef,
  PostTransactionsData
> = z.object({
  customerId: z.nullable(z.string()).optional(),
  object: z.string().optional(),
  currency: z.string().optional(),
  fee: z.nullable(z.string()).optional(),
  amount: z.string(),
  provider: z.string().optional(),
  providerReference: z.string(),
  description: z.nullable(z.string()).optional(),
  status: PostTransactionsStatusResponse$outboundSchema.optional(),
  type: PostTransactionsTypeResponse$outboundSchema.optional(),
  metadata: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(z.any()),
    ]),
  ).optional(),
  origin: z.nullable(PostTransactionsOriginResponse$outboundSchema).optional(),
  declineReason: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  refundedAt: z.nullable(z.string()).optional(),
  paidAt: z.nullable(z.string()).optional(),
  failedAt: z.nullable(z.string()).optional(),
  disputedAt: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsData$ {
  /** @deprecated use `PostTransactionsData$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsData$inboundSchema;
  /** @deprecated use `PostTransactionsData$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsData$outboundSchema;
  /** @deprecated use `PostTransactionsData$Outbound` instead. */
  export type Outbound = PostTransactionsData$Outbound;
}

export function postTransactionsDataToJSON(
  postTransactionsData: PostTransactionsData,
): string {
  return JSON.stringify(
    PostTransactionsData$outboundSchema.parse(postTransactionsData),
  );
}

export function postTransactionsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsData' from JSON`,
  );
}

/** @internal */
export const PostTransactionsResponse$inboundSchema: z.ZodType<
  PostTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostTransactionsData$inboundSchema),
});

/** @internal */
export type PostTransactionsResponse$Outbound = {
  success: boolean;
  data: PostTransactionsData$Outbound;
};

/** @internal */
export const PostTransactionsResponse$outboundSchema: z.ZodType<
  PostTransactionsResponse$Outbound,
  z.ZodTypeDef,
  PostTransactionsResponse
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => PostTransactionsData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionsResponse$ {
  /** @deprecated use `PostTransactionsResponse$inboundSchema` instead. */
  export const inboundSchema = PostTransactionsResponse$inboundSchema;
  /** @deprecated use `PostTransactionsResponse$outboundSchema` instead. */
  export const outboundSchema = PostTransactionsResponse$outboundSchema;
  /** @deprecated use `PostTransactionsResponse$Outbound` instead. */
  export type Outbound = PostTransactionsResponse$Outbound;
}

export function postTransactionsResponseToJSON(
  postTransactionsResponse: PostTransactionsResponse,
): string {
  return JSON.stringify(
    PostTransactionsResponse$outboundSchema.parse(postTransactionsResponse),
  );
}

export function postTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionsResponse' from JSON`,
  );
}
