/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CustomerResponse,
  CustomerResponse$inboundSchema,
  CustomerResponse$Outbound,
  CustomerResponse$outboundSchema,
} from "./customerresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PaginatedData = {
  data: Array<CustomerResponse>;
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  nextCursor: string | null;
  /**
   * The number of data to return (1-100)
   */
  limit?: number | undefined;
};

/** @internal */
export const PaginatedData$inboundSchema: z.ZodType<
  PaginatedData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(CustomerResponse$inboundSchema),
  next_cursor: z.nullable(z.string()),
  limit: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    "next_cursor": "nextCursor",
  });
});

/** @internal */
export type PaginatedData$Outbound = {
  data: Array<CustomerResponse$Outbound>;
  next_cursor: string | null;
  limit: number;
};

/** @internal */
export const PaginatedData$outboundSchema: z.ZodType<
  PaginatedData$Outbound,
  z.ZodTypeDef,
  PaginatedData
> = z.object({
  data: z.array(CustomerResponse$outboundSchema),
  nextCursor: z.nullable(z.string()),
  limit: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    nextCursor: "next_cursor",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaginatedData$ {
  /** @deprecated use `PaginatedData$inboundSchema` instead. */
  export const inboundSchema = PaginatedData$inboundSchema;
  /** @deprecated use `PaginatedData$outboundSchema` instead. */
  export const outboundSchema = PaginatedData$outboundSchema;
  /** @deprecated use `PaginatedData$Outbound` instead. */
  export type Outbound = PaginatedData$Outbound;
}

export function paginatedDataToJSON(paginatedData: PaginatedData): string {
  return JSON.stringify(PaginatedData$outboundSchema.parse(paginatedData));
}

export function paginatedDataFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedData' from JSON`,
  );
}
