/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TooManyRequestsErrorError = {
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const TooManyRequestsErrorError$inboundSchema: z.ZodType<
  TooManyRequestsErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  status: z.number(),
  message: z.string(),
});

/** @internal */
export type TooManyRequestsErrorError$Outbound = {
  code: string;
  status: number;
  message: string;
};

/** @internal */
export const TooManyRequestsErrorError$outboundSchema: z.ZodType<
  TooManyRequestsErrorError$Outbound,
  z.ZodTypeDef,
  TooManyRequestsErrorError
> = z.object({
  code: z.string(),
  status: z.number(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TooManyRequestsErrorError$ {
  /** @deprecated use `TooManyRequestsErrorError$inboundSchema` instead. */
  export const inboundSchema = TooManyRequestsErrorError$inboundSchema;
  /** @deprecated use `TooManyRequestsErrorError$outboundSchema` instead. */
  export const outboundSchema = TooManyRequestsErrorError$outboundSchema;
  /** @deprecated use `TooManyRequestsErrorError$Outbound` instead. */
  export type Outbound = TooManyRequestsErrorError$Outbound;
}

export function tooManyRequestsErrorErrorToJSON(
  tooManyRequestsErrorError: TooManyRequestsErrorError,
): string {
  return JSON.stringify(
    TooManyRequestsErrorError$outboundSchema.parse(tooManyRequestsErrorError),
  );
}

export function tooManyRequestsErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<TooManyRequestsErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TooManyRequestsErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TooManyRequestsErrorError' from JSON`,
  );
}
