/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of transaction
 */
export const TransactionType = {
  Payment: "payment",
  Donation: "donation",
} as const;
/**
 * The type of transaction
 */
export type TransactionType = ClosedEnum<typeof TransactionType>;

/** @internal */
export const TransactionType$inboundSchema: z.ZodNativeEnum<
  typeof TransactionType
> = z.nativeEnum(TransactionType);

/** @internal */
export const TransactionType$outboundSchema: z.ZodNativeEnum<
  typeof TransactionType
> = TransactionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionType$ {
  /** @deprecated use `TransactionType$inboundSchema` instead. */
  export const inboundSchema = TransactionType$inboundSchema;
  /** @deprecated use `TransactionType$outboundSchema` instead. */
  export const outboundSchema = TransactionType$outboundSchema;
}
